/**
 * StaticCssWebpackPlugin
 *
 * Webpack plugin companion untuk tailwind-styled-v4 build-time migration.
 *
 * Masalah yang diselesaikan:
 * - `webpackLoader.ts` di-invoke per-file saat transform. Kalau pakai append-to-file
 *   langsung, ada dua bug: (1) rules lama tidak dibersihkan saat file di-edit/hapus
 *   statenya, (2) duplicate rules kalau file di-transform ulang.
 *
 * Solusi: plugin ini maintain `_fileStaticCssMap: Map<filepath, css>` yang hidup
 * selama proses webpack. Setiap kali loader transform file, ia update Map.
 * Di `compiler.hooks.done`, plugin rebuild `_tw-state-static.css` dari scratch
 * menggunakan seluruh isi Map → selalu fresh, tidak ada stale rules.
 *
 * HMR flow:
 *   File berubah → webpack incremental compilation → loader transform file baru
 *   → `setFileStaticCss(filepath, newCss)` update Map → `done` hook flush Map
 *   → `_tw-state-static.css` berisi state terbaru dari semua file.
 *
 * File dihapus / state dihapus:
 *   Webpack invalidate → loader transform ulang → `setFileStaticCss(filepath, undefined)`
 *   hapus entry dari Map → `done` hook flush → file tidak ada stale rules.
 */

import fs from "node:fs"
import path from "node:path"

// ─────────────────────────────────────────────────────────────────────────────
// Shared singleton Map — persists selama Node.js process hidup (webpack watch)
// ─────────────────────────────────────────────────────────────────────────────
const _fileStaticCssMap = new Map<string, string>()

/**
 * Dipanggil oleh `webpackLoader.ts` setiap kali file di-transform.
 * Pass `undefined` / empty string untuk hapus entry (file tidak punya state CSS).
 */
export function setFileStaticCss(filepath: string, css: string | undefined): void {
  if (css && css.trim()) {
    _fileStaticCssMap.set(filepath, css.trim())
  } else {
    _fileStaticCssMap.delete(filepath)
  }
}

/** Deduplicate + concat semua CSS dari Map */
function buildContent(map: Map<string, string>): string {
  const seen = new Set<string>()
  const rules: string[] = []
  for (const css of map.values()) {
    for (const chunk of css.split(/(?<=\})\s*/)) {
      const rule = chunk.trim()
      if (rule && !seen.has(rule)) {
        seen.add(rule)
        rules.push(rule)
      }
    }
  }
  return rules.join("\n")
}

const HEADER =
  `/* _tw-state-static.css — Auto-generated by tailwind-styled-v4. DO NOT EDIT.\n` +
  ` * Import di globals.css: @import "./_tw-state-static.css";\n` +
  ` * Berisi: state CSS (.tw-s-*[data-*="true"]) + container queries (@container .tw-cq-*).\n` +
  ` * Di-rebuild penuh setiap webpack compilation selesai — tidak ada stale rules.\n` +
  ` */\n\n`

interface WebpackCompiler {
  hooks: {
    done: {
      tap(pluginName: string, callback: () => void): void
    }
  }
}

export class StaticCssWebpackPlugin {
  static readonly PLUGIN_NAME = "TailwindStyledStaticCss"

  private readonly outPath: string

  constructor(safelistPath: string) {
    this.outPath = path.join(path.dirname(safelistPath), "_tw-state-static.css")
  }

  apply(compiler: WebpackCompiler): void {
    compiler.hooks.done.tap(StaticCssWebpackPlugin.PLUGIN_NAME, () => {
      try {
        const content = buildContent(_fileStaticCssMap)
        fs.mkdirSync(path.dirname(this.outPath), { recursive: true })
        fs.writeFileSync(
          this.outPath,
          HEADER + (content || "/* no static rules yet */") + "\n",
          "utf-8"
        )
      } catch (e) {
        console.warn("[tailwind-styled] Could not write _tw-state-static.css:", e)
      }
    })
  }
}