/**
 * tailwind-styled-v5 — Internal API
 * 
 * Re-exports functions needed by other package consumers.
 * All functions require native Rust bindings.
 */

import {
  type NativeBridge,
  type NativeTransformResult,
  type ComponentMetadata,
  type NativeRscResult,
  type LoaderOutput,
  getNativeBridge,
  adaptNativeResult,
  transformSource,
  hasTwUsage,
  isAlreadyTransformed,
  shouldProcess,
  compileCssFromClasses,
  compileCssNative,
  buildStyleTag,
  extractAllClasses,
  extractClassesFromSource,
  astExtractClasses,
  parseClasses,
  normalizeClasses,
  mergeClassesStatic,
  normalizeAndDedupClasses,
  eliminateDeadCss,
  findDeadVariants,
  runElimination,
  optimizeCss,
  scanProjectUsage,
  extractComponentUsage,
  diffClassLists,
  batchExtractClasses,
  checkAgainstSafelist,
  hoistComponents,
  compileVariantTable,
  compileVariants,
  classifyAndSortClasses,
  mergeCssDeclarations,
  analyzeClassUsage,
  analyzeRsc,
  analyzeFile,
  analyzeVariantUsage,
  injectClientDirective,
  injectServerOnlyComment,
  analyzeClasses,
  generateSafelist,
  loadSafelist,
  loadTailwindConfig,
  getContentPaths,
  runLoaderTransform,
  shouldSkipFile,
  fileToRoute,
  getAllRoutes,
  getRouteClasses,
  registerFileClasses,
  registerGlobalClasses,
  getIncrementalEngine,
  resetIncrementalEngine,
  getBucketEngine,
  resetBucketEngine,
  classifyNode,
  detectConflicts,
  bucketSort,
  generateCssForClasses,
  // Static state CSS pre-generation
  extractTwStateConfigs,
  generateStaticStateCss,
  extractAndGenerateStateCss,
  extractContainerCssFromSource,
} from "./index"

export {
  getNativeBridge,
  adaptNativeResult,
  transformSource,
  hasTwUsage,
  isAlreadyTransformed,
  shouldProcess,
  compileCssFromClasses,
  compileCssNative,
  buildStyleTag,
  extractAllClasses,
  extractClassesFromSource,
  astExtractClasses,
  parseClasses,
  normalizeClasses,
  mergeClassesStatic,
  normalizeAndDedupClasses,
  eliminateDeadCss,
  findDeadVariants,
  runElimination,
  optimizeCss,
  scanProjectUsage,
  extractComponentUsage,
  diffClassLists,
  batchExtractClasses,
  checkAgainstSafelist,
  hoistComponents,
  compileVariantTable,
  compileVariants,
  classifyAndSortClasses,
  mergeCssDeclarations,
  analyzeClassUsage,
  analyzeRsc,
  analyzeFile,
  analyzeVariantUsage,
  injectClientDirective,
  injectServerOnlyComment,
  analyzeClasses,
  generateSafelist,
  loadSafelist,
  loadTailwindConfig,
  getContentPaths,
  runLoaderTransform,
  shouldSkipFile,
  fileToRoute,
  getAllRoutes,
  getRouteClasses,
  registerFileClasses,
  registerGlobalClasses,
  getIncrementalEngine,
  resetIncrementalEngine,
  getBucketEngine,
  resetBucketEngine,
  classifyNode,
  detectConflicts,
  bucketSort,
  generateCssForClasses,
  // Static state + container CSS pre-generation
  extractTwStateConfigs,
  generateStaticStateCss,
  extractAndGenerateStateCss,
  extractContainerCssFromSource,
}

export { type NativeBridge, type NativeTransformResult, type ComponentMetadata, type NativeRscResult, type LoaderOutput }

export type CssCompileResult = NativeTransformResult

// CSS pipeline — Tailwind → LightningCSS
// PHASE 0: Includes LRU caching for 30-40% performance improvement
export { runCssPipeline, runCssPipelineSync, generateRawCss, getCacheStats, clearCache, type CssPipelineResult } from "./tailwindEngine"