/**
 * tailwind-styled-v5 — Internal API
 * 
 * Re-exports functions needed by other package consumers.
 * All functions require native Rust bindings.
 */

import {
  type NativeBridge,
  type NativeTransformResult,
  type ComponentMetadata,
  type NativeRscResult,
  type LoaderOutput,
  getNativeBridge,
  adaptNativeResult,
  transformSource,
  hasTwUsage,
  isAlreadyTransformed,
  shouldProcess,
  compileCssFromClasses,
  compileCssNative,
  buildStyleTag,
  extractAllClasses,
  extractClassesFromSource,
  astExtractClasses,
  parseClasses,
  normalizeClasses,
  mergeClassesStatic,
  normalizeAndDedupClasses,
  eliminateDeadCss,
  findDeadVariants,
  runElimination,
  optimizeCss,
  scanProjectUsage,
  extractComponentUsage,
  diffClassLists,
  batchExtractClasses,
  checkAgainstSafelist,
  hoistComponents,
  compileVariantTable,
  compileVariants,
  classifyAndSortClasses,
  mergeCssDeclarations,
  analyzeClassUsage,
  analyzeRsc,
  analyzeFile,
  analyzeVariantUsage,
  injectClientDirective,
  injectServerOnlyComment,
  analyzeClasses,
  generateSafelist,
  loadSafelist,
  loadTailwindConfig,
  getContentPaths,
  runLoaderTransform,
  shouldSkipFile,
  fileToRoute,
  getAllRoutes,
  getRouteClasses,
  registerFileClasses,
  registerGlobalClasses,
  getIncrementalEngine,
  resetIncrementalEngine,
  getBucketEngine,
  resetBucketEngine,
  classifyNode,
  detectConflicts,
  bucketSort,
  generateCssForClasses,
} from "./index"

export {
  getNativeBridge,
  adaptNativeResult,
  transformSource,
  hasTwUsage,
  isAlreadyTransformed,
  shouldProcess,
  compileCssFromClasses,
  compileCssNative,
  buildStyleTag,
  extractAllClasses,
  extractClassesFromSource,
  astExtractClasses,
  parseClasses,
  normalizeClasses,
  mergeClassesStatic,
  normalizeAndDedupClasses,
  eliminateDeadCss,
  findDeadVariants,
  runElimination,
  optimizeCss,
  scanProjectUsage,
  extractComponentUsage,
  diffClassLists,
  batchExtractClasses,
  checkAgainstSafelist,
  hoistComponents,
  compileVariantTable,
  compileVariants,
  classifyAndSortClasses,
  mergeCssDeclarations,
  analyzeClassUsage,
  analyzeRsc,
  analyzeFile,
  analyzeVariantUsage,
  injectClientDirective,
  injectServerOnlyComment,
  analyzeClasses,
  generateSafelist,
  loadSafelist,
  loadTailwindConfig,
  getContentPaths,
  runLoaderTransform,
  shouldSkipFile,
  fileToRoute,
  getAllRoutes,
  getRouteClasses,
  registerFileClasses,
  registerGlobalClasses,
  getIncrementalEngine,
  resetIncrementalEngine,
  getBucketEngine,
  resetBucketEngine,
  classifyNode,
  detectConflicts,
  bucketSort,
  generateCssForClasses,
}

export { type NativeBridge, type NativeTransformResult, type ComponentMetadata, type NativeRscResult, type LoaderOutput }

export type CssCompileResult = NativeTransformResult