/**
 * tailwind-styled-v4 — safelistGenerator
 *
 * Scan semua source files dan extract Tailwind classes untuk safelist.
 * Output: .tailwind-styled-safelist.json
 *
 * Developer tidak perlu manual safelist.
 */

import fs from "node:fs"
import path from "node:path"
import { getNativeBridge } from "./nativeBridge"
import { extractAllClasses } from "./classExtractor"
import { parseSafelistJson } from "./schemas"

const SCAN_EXTENSIONS = [".tsx", ".ts", ".jsx", ".js"]

function scanDir(dir: string, files: string[] = []): string[] {
  if (!fs.existsSync(dir)) return files

  const entries = fs.readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".next" || entry.name === "dist") continue
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      scanDir(fullPath, files)
    } else if (SCAN_EXTENSIONS.some((ext) => entry.name.endsWith(ext))) {
      files.push(fullPath)
    }
  }
  return files
}

export function generateSafelist(
  scanDirs: string[],
  outputPath = ".tailwind-styled-safelist.json",
  cwd = process.cwd()
): string[] {
  const allClasses = new Set<string>()

  const native = getNativeBridge()
  const allFiles: string[] = []
  for (const dir of scanDirs) {
    const absDir = path.isAbsolute(dir) ? dir : path.resolve(cwd, dir)
    scanDir(absDir, allFiles)
  }

  // Fast path: Rust parallel batch extraction
  if (native?.batchExtractClassesNative && allFiles.length > 0) {
    const results = native.batchExtractClassesNative(allFiles) as Array<{
      file: string; classes: string[]; ok: boolean
    }>
    for (const r of results ?? []) {
      if (r.ok) r.classes.forEach((c: string) => allClasses.add(c))
    }
  } else {
    // JS sequential fallback
    for (const file of allFiles) {
      try {
        const source = fs.readFileSync(file, "utf-8")
        extractAllClasses(source).forEach((c) => allClasses.add(c))
      } catch (err) { /* intentionally silent — candidate miss */ }
    }
  }

  const sorted = Array.from(allClasses).sort()
  const absOutput = path.isAbsolute(outputPath) ? outputPath : path.resolve(cwd, outputPath)

  fs.writeFileSync(absOutput, JSON.stringify(sorted, null, 2))
  console.log(`[tailwind-styled-v4] Safelist: ${sorted.length} classes → ${absOutput}`)

  return sorted
}

export function loadSafelist(safelistPath: string): string[] {
  try {
    const content = fs.readFileSync(safelistPath, "utf-8")
    return parseSafelistJson(content) ?? []
  } catch {
    return []
  }
}

/**
 * Tailwind v4 variant — output CSS dengan @source inline() bukan JSON.
 * Tailwind v4 tidak punya 'safelist' di config — pakai @source inline() di CSS.
 */
export function generateSafelistCss(
  scanDirs: string[],
  outputPath = "src/app/__tw-safelist.css",
  cwd = process.cwd()
): string[] {
  const allClasses = new Set<string>()
  const native = getNativeBridge()

  const allFiles2: string[] = []
  for (const dir of scanDirs) {
    const absDir = path.isAbsolute(dir) ? dir : path.resolve(cwd, dir)
    scanDir(absDir, allFiles2)
  }

  if (native?.batchExtractClassesNative && allFiles2.length > 0) {
    const results = native.batchExtractClassesNative(allFiles2) as Array<{
      file: string; classes: string[]; ok: boolean
    }>
    for (const r of results ?? []) {
      if (r.ok) r.classes.forEach((c: string) => allClasses.add(c))
    }
  } else {
    for (const file of allFiles2) {
      try {
        const source = fs.readFileSync(file, "utf-8")
        extractAllClasses(source).forEach((c) => allClasses.add(c))
      } catch (err) { /* intentionally silent — candidate miss */ }
    }
  }

  const sorted = Array.from(allClasses).sort()
  const absOutput = path.isAbsolute(outputPath) ? outputPath : path.resolve(cwd, outputPath)

  fs.mkdirSync(path.dirname(absOutput), { recursive: true })

  const css =
    sorted.length > 0
      ? `/* Auto-generated by tailwind-styled-v4 — DO NOT EDIT */
@source inline("${sorted.join(" ")}");
`
      : `/* Auto-generated by tailwind-styled-v4 — DO NOT EDIT */
/* No safelist classes found */
`

  fs.writeFileSync(absOutput, css)
  console.log(`[tailwind-styled-v4] Safelist: ${sorted.length} classes → ${absOutput}`)

  return sorted
}
