/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyse a list of (file, classes[]) pairs and return a full report.
 *
 * `files_json` is a JSON string: `[{"file":"...","classes":["cls1","cls2"]},...]`
 * This mirrors the ScanWorkspaceResult shape from @tailwind-styled/scanner.
 */
export declare function analyzeClasses(filesJson: string, root: string, topN: number): AnalyzerReport

/**
 * Analisis class usage dari scan result JSON.
 *
 * Menggantikan sebagian `BundleAnalyzer.analyzeClass()` di bundleAnalyzer.ts.
 * Batch analysis: process banyak classes sekaligus via HashMap.
 */
export declare function analyzeClassUsage(classes: Array<string>, scanResultJson: string, css: string): Array<ClassBundleInfo>

/**
 * Analisis distribusi classes per route — untuk CSS code splitting.
 *
 * Menggantikan routeCssCollector.ts logic.
 * Dipakai oleh `tw split` untuk generate per-route CSS bundles.
 *
 * Input JSON: Record<route, string[]> — map route ke daftar file
 * files_json: JSON scan result dengan file-to-class mapping
 */
export declare function analyzeRouteClassDistribution(routeFilesJson: string, scanResultJson: string): Array<RouteClassMap>

export interface AnalyzerReport {
  root: string
  totalFiles: number
  uniqueClassCount: number
  totalClassOccurrences: number
  topClasses: Array<ClassCount>
  duplicateCandidates: Array<ClassCount>
  /** Safelist: all classes that must be retained regardless of usage */
  safelist: Array<string>
}

export declare function analyzeRsc(source: string, filename: string): RscAnalysis

/**
 * Generate a stable cache key for an animation options object.
 *
 * Replaces `animationCacheKey(opts)` in `animate/src/registry.ts`.
 *
 * Input JSON: `{ from, to, duration?, easing?, delay?, fill?, iterations?, direction?, name? }`
 * Output: deterministic JSON string suitable for Map key.
 */
export declare function animationCacheKey(optsJson: string): string

/**
 * Apply class diff: `(existing ∪ added) ∖ removed` → class list baru.
 *
 * **Menggantikan** `applyClassDiff()` di `engine/src/incremental.ts`.
 *
 * Lebih stabil dari JS Set karena tidak ada GC pause saat Set di-reallocate.
 * Untuk class list besar (500+ entries), Rust HashSet ~3x lebih cepat.
 */
export declare function applyClassDiff(existing: Array<string>, added: Array<string>, removed: Array<string>): Array<string>

/**
 * Cek apakah dua class array berisi elemen identik (order-independent).
 *
 * **Menggantikan** `areClassSetsEqual()` di `engine/src/incremental.ts`.
 *
 * Single-pass HashSet lookup: O(n+m) vs JS yang buat `new Set(b)` tiap call.
 */
export declare function areClassSetsEqual(a: Array<string>, b: Array<string>): boolean

/**
 * Parse a source file and extract Tailwind classes using AST-level analysis.
 * More accurate than regex-only approaches — handles JSX, template literals,
 * and object configs. Implements the same interface as the oxc-based scanner.
 */
export declare function astExtractClasses(source: string, filename: string): AstExtractResult

export interface AstExtractResult {
  /** All Tailwind classes found in the file */
  classes: Array<string>
  /** Component names found (const Foo = tw.div`...`) */
  componentNames: Array<string>
  /** Whether any tw.* usage was found */
  hasTwUsage: boolean
  /** Whether the file has "use client" directive */
  hasUseClient: boolean
  /** Import statements found */
  imports: Array<string>
}

/** Get registry size for diagnostics. */
export declare function atomicRegistrySize(): number

/** Current registry size — for observability. */
export declare function atomicRegistrySize(): number

export interface AtomicRule {
  twClass: string
  atomicName: string
  property: string
  value: string
  modifier?: string
}

/**
 * Extract classes dari banyak files sekaligus secara parallel.
 *
 * Menggantikan loop JS di scanner yang process satu file per giliran.
 * Menggunakan Rayon thread pool yang sudah ada untuk parallel I/O + regex.
 *
 * # Performance
 * Pada proyek 200 file: ~8-12x lebih cepat dari JS sequential loop
 * karena parallel I/O dan tidak ada event loop overhead.
 */
export declare function batchExtractClasses(filePaths: Array<string>): Array<BatchExtractResult>

export interface BatchExtractResult {
  /** File path */
  file: string
  /** Classes yang diekstrak */
  classes: Array<string>
  /** Hash content file (untuk cache invalidation) */
  contentHash: string
  /** Apakah file berhasil diproses */
  ok: boolean
  /** Error message jika gagal */
  error?: string
}

/**
 * Split class menjadi komponen-komponen: variant, base, modifier.
 *
 * Menggantikan splitVariantAndBase() di semantic.ts dan utilityPrefix() logic.
 * Batch mode untuk dipakai oleh CLI dan analyzer.
 *
 * Contoh: "dark:hover:bg-blue-500/50"
 *   → { variantKey: "dark:hover", base: "bg-blue-500", modifier: "50", ... }
 */
export declare function batchSplitClasses(classes: Array<string>): Array<VariantSplitResult>

export interface BucketedClass {
  className: string
  bucket: string
  sortOrder: number
}

/**
 * Generate `@container` CSS rules dari breakpoints.
 *
 * **Menggantikan** `buildContainerRules()` dan `generateContainerCss()`
 * di `core/src/containerQuery.ts`.
 *
 * Output format identik dengan JS:
 * ```css
 * @container (min-width: 320px){.tw-cq-abc123{display:flex;flex-direction:column}}
 * @container sidebar (min-width: 1024px){.tw-cq-abc123{display:grid}}
 * ```
 *
 * # Arguments
 * - `id`             — unique hash ID komponen (mis. "tw-cq-abc123")
 * - `breakpoints`    — array {key, classes} — key bisa nama ("sm") atau raw px ("480px")
 * - `container_name` — nama container opsional untuk `@container <name> (...)`
 */
export declare function buildContainerRules(id: string, breakpoints: Array<ContainerBreakpoint>, containerName?: string | undefined | null): string

/**
 * Build the variant dependency chain for a Tailwind class.
 *
 * `"md:hover:bg-red-500"` → `["md:", "md:hover:"]`
 * `"bg-red-500"`          → `[]`  (no variant prefix)
 *
 * One-pass, zero regex, O(n) where n = number of variant segments.
 */
export declare function buildDependencyChain(className: string): Array<string>

/**
 * Compute usage frequency distribution for a list of class usages.
 *
 * Replaces `buildDistribution(usages: ClassUsage[])` in `analyzeWorkspace.ts`.
 *
 * Input JSON: `[{ "name": "bg-red-500", "count": 3 }, ...]`
 * Output: `{ once, few, moderate, frequent }` — bucket counts.
 *
 * Bucket semantics (same as JS original):
 *   once     = count === 1
 *   few      = count 2–3
 *   moderate = count 4–7
 *   frequent = count 8+
 */
export declare function buildDistribution(usagesJson: string): ClassDistribution

/**
 * Build lookup key untuk `__generatedRegistry` — migrated dari `lookupGenerated()` di cv.ts.
 *
 * JS original:
 * ```ts
 * const key = Object.keys(merged)
 *   .sort()
 *   .filter((k) => k !== "className")
 *   .map((k) => `${k}:${String(merged[k])}`)
 *   .join("|")
 * ```
 *
 * Rust version: satu allocation, zero intermediate arrays.
 * Called setiap render jika komponen punya `componentId` — worth di-native.
 *
 * # Input
 * - `default_variants_json`: JSON `Record<string, string>` dari defaultVariants
 * - `props_json`: JSON `Record<string, string | number | boolean>` dari props
 *
 * # Output
 * Key string seperti `"size:lg|variant:solid"`
 */
export declare function buildVariantLookupKey(defaultVariantsJson: string, propsJson: string): string

export interface BundleContribution {
  className: string
  sizeBytes: number
  variantChains: Array<string>
  dependencies: Array<string>
  inCss: boolean
}

export interface CacheEntry {
  file: string
  classes: Array<string>
  hash: string
  mtimeMs: number
  size: number
  hitCount: number
}

/**
 * Compute priority score for a file (SmartCache logic in Rust).
 * Higher score = process first.
 */
export declare function cachePriority(mtimeMs: number, size: number, cachedMtimeMs: number, cachedSize: number, cachedHitCount: number, cachedLastSeenMs: number, nowMs: number): number

/**
 * Read a scanner cache JSON file into structured entries.
 * Replaces the JS `ScanCache.read()` method.
 */
export declare function cacheRead(cachePath: string): CacheReadResult

export interface CacheReadResult {
  entries: Array<CacheEntry>
  version: number
}

/** Stats hasil komputasi disk cache. */
export interface CacheStatsResult {
  totalEntries: number
  totalClasses: number
  totalSizeBytes: number
  /** Rata-rata jumlah class per entry (× 100 untuk 2 desimal tanpa float issue). */
  avgClassesPerEntryX100: number
  /** Top-10 class paling sering muncul lintas file. */
  mostUsedClasses: Array<ClassFrequency>
}

/**
 * Write cache entries to a JSON cache file.
 * Replaces the JS `ScanCache.save()` method.
 */
export declare function cacheWrite(cachePath: string, entries: Array<CacheEntry>): boolean

/**
 * Hitung bundle contribution untuk satu atau banyak classes dari CSS.
 *
 * Menggantikan calculateBundleContribution() + extractVariantChains() +
 * extractDependencies() di bundleAnalyzer.ts.
 *
 * Batch mode: process semua classes sekaligus dengan satu CSS scan.
 * Lebih efisien dari JS yang scan CSS satu kali per class.
 */
export declare function calculateBundleContributions(classes: Array<string>, css: string): Array<BundleContribution>

/**
 * Full impact calculation: risk + savings + suggestions in one native call.
 *
 * Input JSON: `{ className, totalComponents, indirectUsage, bundleSizeBytes }`
 * Output JSON: `{ riskLevel, estimatedSavings, suggestions }`
 *
 * JS equivalent: three separate calls to calculateRisk + calculateSavings + generateSuggestions
 */
export declare function calculateImpact(impactJson: string): string

/**
 * Hitung impact score per class — usage × size weighted.
 *
 * Menggantikan logic yang tersebar di impactTracker.ts + bundleAnalyzer.ts.
 * Dipakai oleh `tw analyze` untuk ranking class berdasarkan dampak ke bundle.
 *
 * Formula: impact = (usage_weight * usage_score) + (size_weight * size_score)
 */
export declare function calculateImpactScores(classes: Array<string>, scanResultJson: string, css: string, usageWeight?: number | undefined | null, sizeWeight?: number | undefined | null): Array<ImpactScore>

/**
 * Calculate risk level for a single class.
 *
 * JS equivalent: `calculateRisk(className, impact): "low" | "medium" | "high"`
 */
export declare function calculateRisk(className: string, totalComponents: number): string

/**
 * Calculate risk level for a class based on usage count and critical patterns.
 *
 * Replaces `calculateRisk(className, impact)` in `ImpactTracker`.
 *
 * Input: class name + ImpactReport JSON.
 * Returns: `"low"` | `"medium"` | `"high"`
 */
export declare function calculateRisk(className: string, impactJson: string): string

/**
 * Calculate estimated bundle savings.
 *
 * JS equivalent: `calculateSavings(bundleSize, componentCount): number`
 */
export declare function calculateSavings(bundleSizeBytes: number, componentCount: number): number

/**
 * Estimate bundle savings from removing a class.
 *
 * Replaces `calculateSavings(bundleSize, componentCount)` in `ImpactTracker`.
 */
export declare function calculateSavings(bundleSize: number, componentCount: number): number

/**
 * Cek daftar classes terhadap safelist.
 *
 * Menggantikan Array.filter().includes() di JS yang O(n*m).
 * HashSet lookup: O(1) per class → O(n) total.
 */
export declare function checkAgainstSafelist(classes: Array<string>, safelist: Array<string>): SafelistCheckResult

export interface ClassBundleInfo {
  className: string
  usageCount: number
  filesJson: string
  bundleSizeBytes: number
  isDeadCode: boolean
}

export interface ClassConflict {
  group: string
  variantKey: string
  classes: Array<string>
  message: string
}

export interface ClassCount {
  name: string
  count: number
}

export interface ClassDiffResult {
  /** Classes yang ada di `current` tapi tidak di `previous` */
  added: Array<string>
  /** Classes yang ada di `previous` tapi tidak di `current` */
  removed: Array<string>
  /** Classes yang ada di keduanya */
  unchanged: Array<string>
  /** Apakah ada perubahan */
  hasChanges: boolean
}

export interface ClassDistribution {
  /** Classes that appear exactly once */
  once: number
  /** Classes that appear 2–3 times */
  few: number
  /** Classes that appear 4–7 times */
  moderate: number
  /** Classes that appear 8+ times */
  frequent: number
}

export interface ClassExtractResult {
  classes: Array<string>
  componentNames: Array<string>
  hasTwUsage: boolean
  hasUseClient: boolean
  imports: Array<string>
}

export interface ClassFrequency {
  class: string
  count: number
}

/**
 * Classify dan sort Tailwind classes berdasarkan CSS property bucket.
 *
 * Menggantikan `classifyIntoBuckets` + `sortByBucket` di styleBucketSystem.ts.
 * Bucket ordering: reset → layout → spacing → sizing → typography → visual
 *                  → interaction → responsive → unknown
 *
 * # Performance
 * HashMap lookup O(1) vs JS object lookup dengan prototype chain overhead.
 */
export declare function classifyAndSortClasses(classes: Array<string>): Array<BucketedClass>

/**
 * Classify classes sebagai known/unknown Tailwind utilities.
 *
 * Menggantikan `isKnownTailwindClass()` + `utilityPrefix()` di semantic.ts.
 * Batch mode: process banyak classes sekaligus via HashSet lookups.
 */
export declare function classifyKnownClasses(classes: Array<string>, safelist: Array<string>, customUtilities: Array<string>): Array<KnownClassResult>

/** Result dari compute_class_stats */
export interface ClassStatsResult {
  totalClassOccurrences: number
  /** JSON array ClassUsage[] — top N by count */
  topJson: string
  /** JSON array ClassUsage[] — count >= frequent_threshold, max top_limit items */
  frequentJson: string
  /** JSON array ClassUsage[] — count === 1 */
  uniqueJson: string
}

export interface ClassToken {
  raw: string
  type: string
}

export interface ClassUsageResult {
  className: string
  specificity: number
  isOverride: boolean
  variants: Array<string>
}

/**
 * Clear the global atomic registry.
 * JS equivalent: `clearAtomicRegistry()`
 */
export declare function clearAtomicRegistry(): void

/**
 * Evict all entries from the atomic rule registry.
 *
 * Replaces `clearAtomicRegistry()` in `atomic/src/index.ts`.
 */
export declare function clearAtomicRegistry(): void

/** Hapus semua entries dari kedua registry — useful untuk test isolation. */
export declare function clearNameRegistries(): void

/**
 * Aggregate class counts from a list of (file, classes[]) scan entries.
 *
 * Replaces `collectClassCounts(scan: ScanWorkspaceResult)` in `analyzeWorkspace.ts`.
 *
 * Input JSON: `[{ "file": "...", "classes": ["cls1", "cls2"] }, ...]`
 * Output JSON: `[{ "name": "cls1", "count": 3 }, ...]` sorted by count desc, name asc.
 */
export declare function collectClassCounts(filesJson: string): Array<ClassCount>

/**
 * Kumpulkan semua file yang cocok secara rekursif dari `root`.
 *
 * **Menggantikan** `collectFiles()` di `parallel-scanner.ts`.\
 * JS version: `fs.readdirSync` + rekursi + manual ignore check — lambat di
 * workspace besar karena setiap syscall harus lewat JS event loop.\
 * Rust version: satu rekursi native tanpa overhead — 2–5× lebih cepat
 * untuk workspace 500+ file.
 *
 * Hanya mengembalikan file paths (tidak membaca konten) — ringan dan cepat.
 * Dipakai oleh parallel-scanner sebelum split ke worker chunks.
 *
 * # Arguments
 * - `root` — root direktori yang akan di-walk
 * - `extensions` — daftar ekstensi yang diterima (mis. `[".ts", ".tsx"]`)
 * - `ignore_dirs` — nama direktori yang diabaikan (mis. `["node_modules"]`)
 */
export declare function collectFiles(root: string, extensions?: Array<string> | undefined | null, ignoreDirs?: Array<string> | undefined | null): Array<string>

/** Compile a from/to animation into @keyframes + animation CSS. */
export declare function compileAnimation(from: string, to: string, name?: string | undefined | null, durationMs?: number | undefined | null, easing?: string | undefined | null, delayMs?: number | undefined | null, fill?: string | undefined | null, iterations?: string | undefined | null, direction?: string | undefined | null): CompiledAnimation

/**
 * Backward compat — sekarang input adalah raw CSS, bukan class names.
 * CSS harus datang dari Tailwind JS engine.
 */
export declare function compileCss(css: string, prefix?: string | undefined | null): CssCompileResult

/** Alias untuk backward compat. */
export declare function compileCssLightning(css: string, prefix?: string | undefined | null): CssCompileResult

export interface CompiledAnimation {
  className: string
  keyframesCss: string
  animationCss: string
}

export interface CompiledTheme {
  /** Theme name (e.g. "light", "dark", "brand") */
  name: string
  /** CSS selector for this theme (e.g. ":root", "[data-theme='dark']") */
  selector: string
  /** Full CSS block: selector { --token-name: value; ... } */
  css: string
  /** All tokens in this theme */
  tokens: Array<ThemeToken>
}

/**
 * Compile a custom multi-stop @keyframes definition.
 *
 * `stops_json`: `[{"stop":"0%","classes":"opacity-0 scale-95"},...]`
 */
export declare function compileKeyframes(name: string, stopsJson: string): CompiledAnimation

/**
 * Parse a token map JSON and compile it into a CSS variable block.
 *
 * `tokens_json`: `{"color":{"primary":"#3b82f6","secondary":"#8b5cf6"},"spacing":{"sm":"0.5rem"}}`
 * `theme_name`:  "light" | "dark" | "brand" | etc.
 * `prefix`:      CSS variable prefix, e.g. "tw" → `--tw-color-primary`
 */
export declare function compileTheme(tokensJson: string, themeName: string, prefix: string): CompiledTheme

/**
 * Compile semua kombinasi variant component ke lookup table.
 *
 * Menggantikan `compileAllVariantCombinations` di staticVariantCompiler.ts.
 * Hasilkan semua permutasi variant → merged className di build time.
 * Runtime hanya perlu O(1) lookup, zero computation.
 *
 * # Input JSON format
 * ```json
 * {
 *   "componentId": "Button",
 *   "base": "px-4 py-2 font-medium",
 *   "variants": { "size": { "sm": "h-8 text-sm", "lg": "h-12 text-lg" } },
 *   "defaultVariants": { "size": "sm" }
 * }
 * ```
 */
export declare function compileVariantTable(configJson: string): VariantTableResult

export interface ComponentPropUsage {
  /** Nama component (PascalCase) */
  component: string
  /** Map prop → daftar nilai yang dipakai di JSX */
  propsJson: string
}

/**
 * Hitung stats dari disk cache entries — class frequency count + top-10 sort.
 *
 * **Menggantikan** `computeCacheStats()` di `scanner/cache-native.ts`.
 *
 * JS: `new Map<string,number>()` + manual count loop + `.sort()` + `.slice(0,10)`.
 *     Untuk 5000 entries × 30 classes = 150,000 Map.set() calls di V8.
 * Rust: `HashMap::with_capacity` + direct count + partial_sort via select_nth_unstable.
 *       ~3× lebih cepat untuk workspace besar, tanpa GC pressure.
 *
 * # Arguments
 * - `files_classes` — array per-file class lists (parallel ke `entries`)
 * - `sizes`         — array size bytes per entry (harus sama panjang)
 * - `top`           — berapa top classes yang dikembalikan (default 10)
 */
export declare function computeCacheStats(filesClasses: Array<Array<string>>, sizes: Array<number>, top?: number | undefined | null): CacheStatsResult

/**
 * Menggantikan JS stats aggregation di analyzeWorkspace.ts:
 * ```ts
 * const top = all.slice(0, topLimit)
 * const frequent = all.filter(u => u.count >= frequentThreshold).slice(0, topLimit)
 * const unique = all.filter(u => u.count === 1)
 * const totalClassOccurrences = all.reduce((sum, u) => sum + u.count, 0)
 * ```
 *
 * Input: JSON array ClassUsage[] sudah di-sort by count desc dari buildClassUsage()
 * Output: ClassStatsResult dengan semua 4 nilai sekaligus (satu pass)
 */
export declare function computeClassStats(usagesJson: string, topLimit: number, frequentThreshold: number): ClassStatsResult

/**
 * Compute full risk + suggestions in a single native call — avoids double JSON
 * serialization when called from `calculateImpact()` in JS.
 *
 * Returns `{ riskLevel: string, suggestions: string[] }` as JSON.
 */
export declare function computeImpactMetadata(className: string, impactJson: string): string

/**
 * Compute an incremental diff between a previous scan result and a new file scan.
 *
 * `previous_json`: JSON array of `{file, classes, hash}` from last scan.
 * `current_json`:  JSON array of `{file, classes, hash}` from current scan.
 *
 * Returns which classes were added/removed and which files changed.
 */
export declare function computeIncrementalDiff(previousJson: string, currentJson: string): IncrementalDiff

export interface ConflictDetectionResult {
  conflicts: Array<ClassConflict>
  conflictedClassNames: Array<string>
}

/** Satu breakpoint entry untuk `build_container_rules`. */
export interface ContainerBreakpoint {
  /** Key breakpoint (mis. "sm", "lg") atau raw minWidth (mis. "480px") */
  key: string
  /** Class string untuk breakpoint ini (mis. "flex-col text-sm") */
  classes: string
}

/**
 * Generate a short fingerprint string from a list of parts.
 *
 * Replaces `createFingerprint(parts: string[])` in `engine/src/ir.ts`.
 *
 * Algorithm: FNV-1a variant over all bytes of all parts (separated by `\x00`).
 * Returns a base-36 string, e.g. `"1k7z3p"`.
 *
 * Why faster than JS:
 * - No string → char array overhead
 * - No `reduce()` closure allocations per character
 * - Math.abs not needed — u64 wrapping is always non-negative
 */
export declare function createFingerprint(parts: Array<string>): string

export interface CssCompileResult {
  css: string
  sizeBytes: number
  resolvedClasses: Array<string>
  unknownClasses: Array<string>
}

export interface CssDeclarationMap {
  /** JSON: Record<string, string> — property → value (last wins) */
  declarationsJson: string
  /** Reconstructed declaration string: "prop: val; prop: val" */
  declarationString: string
  /** Number of declarations parsed */
  count: number
}

export interface CssRuleLookup {
  className: string
  property: string
  value: string
  isImportant: boolean
  variants: Array<string>
  specificity: number
}

export interface CssThemeVar {
  /** Variable name without leading `--`, e.g. `color-primary` */
  key: string
  /** Raw value from CSS, e.g. `#3b82f6` or `var(--color-base)` */
  value: string
}

export interface DeadCodeResult {
  deadInCss: Array<string>
  deadInSource: Array<string>
  liveClasses: Array<string>
  totalCssClasses: number
  totalSourceClasses: number
}

/** Satu entry deklarasi CSS untuk `declaration_map_to_string`. */
export interface DeclarationEntry {
  property: string
  value: string
}

/**
 * Serialize ordered declaration entries menjadi inline CSS string.
 *
 * **Menggantikan** `declarationMapToString()` di `analyzer/src/classToCss.ts`.
 *
 * Input adalah array ordered entries — urutan dipertahankan (last-write-wins
 * dari merge sebelumnya sudah ditangani JS side).
 *
 * # Examples
 * ```
 * declaration_map_to_string(vec![
 *     DeclarationEntry { property: "color".into(), value: "red".into() },
 *     DeclarationEntry { property: "padding".into(), value: "1rem".into() },
 * ])
 * // "color: red; padding: 1rem"
 * ```
 */
export declare function declarationMapToString(entries: Array<DeclarationEntry>): string

/**
 * Deteksi konflik antara Tailwind classes yang di-pakai bersamaan.
 *
 * Menggantikan `detectConflicts()` di semantic.ts.
 * Contoh: `["bg-red-500", "bg-blue-500"]` → conflict group "bg".
 *
 * Input JSON: `[{ "name": "bg-red-500", "count": 3 }, ...]`
 */
export declare function detectClassConflicts(usagesJson: string): ConflictDetectionResult

/**
 * Deteksi dead code antara CSS output dan source scan result.
 *
 * Menggantikan detectDeadCode() + checkIsDeadCode() di bundleAnalyzer.ts.
 * Single O(n+m) pass via HashSet — jauh lebih efisien dari
 * JS yang scan CSS per-class: O(n*m).
 */
export declare function detectDeadCode(scanResultJson: string, css: string): DeadCodeResult

/**
 * Hitung diff antara dua class lists.
 *
 * Dipakai oleh incremental compiler untuk mendeteksi perubahan
 * class yang perlu recompile — lebih efisien dari full string compare.
 *
 * # Performance
 * HashSet-based diff: O(n+m) vs JS array indexOf O(n*m).
 */
export declare function diffClassLists(previous: Array<string>, current: Array<string>): ClassDiffResult

export declare function extractAllClasses(source: string): Array<string>

/**
 * Extract Tailwind classes from a single source file's content.
 * Handles tw`...`, tw.tag`...`, className="...", class="..." patterns.
 * ─ OPTIMIZATION (Phase 2.3): Parallel regex pattern matching
 */
export declare function extractClassesFromSource(source: string): Array<string>

export declare function extractClassesFromSource(source: string): ClassExtractResult

/**
 * Extract semua JSX component usage dari source code.
 *
 * Menggantikan `extractComponentUsage` di deadStyleEliminator.ts.
 * Mencari pola `<ComponentName prop="value" />` dan mengekstrak
 * static prop values untuk dead style elimination.
 *
 * # Performance
 * Regex-based scan: ~2-5x lebih cepat dari JS equivalent karena
 * regex engine Rust tidak perlu GC pauses dan memory layout lebih cache-friendly.
 */
export declare function extractComponentUsage(source: string): Array<ComponentPropUsage>

/**
 * Extract CSS variables referenced in a source file.
 * Returns a list of `--var-name` strings found.
 */
export declare function extractCssVars(source: string): Array<string>

/**
 * Parse `@theme { --key: value; }` blocks from a CSS string.
 *
 * Returns all key-value pairs found inside `@theme` blocks.
 * Handles multiple `@theme` blocks and strips leading `--`.
 *
 * Menggantikan JS regex di `themeReader.ts extractThemeFromCSS()`.
 */
export declare function extractThemeFromCss(css: string): Array<CssThemeVar>

export interface FileChangeDiff {
  added: Array<string>
  removed: Array<string>
}

export interface FileScanEntry {
  file: string
  classes: Array<string>
  hash: string
}

/**
 * Generate CSS string from an array of AtomicRule JSON.
 *
 * Input JSON: `Array<AtomicRule>`
 * Output: CSS string
 *
 * JS equivalent: `generateAtomicCss(rules: AtomicRule[]): string`
 */
export declare function generateAtomicCss(rulesJson: string): string

/**
 * Generate CSS string from a list of AtomicRules.
 *
 * Replaces `generateAtomicCss(rules)` in `atomic/src/index.ts`.
 * Input JSON: `[{ twClass, atomicName, property, value, modifier? }, ...]`
 */
export declare function generateAtomicCss(rulesJson: string): string

/**
 * Scan workspace untuk semua sub-component names yang dipakai,
 * lalu generate TypeScript declaration file untuk type inference otomatis.
 *
 * Output .d.ts berisi module augmentation yang membuat TypeScript
 * tahu nama sub-component tanpa user perlu declare manual.
 */
export declare function generateSubComponentTypes(root: string, outputPath?: string | undefined | null): SubComponentScanResult

/**
 * Generate human-readable suggestions for a class based on impact analysis.
 *
 * Replaces `generateSuggestions(className, impact)` in `ImpactTracker`.
 *
 * Input: class name + ImpactReport JSON (with riskLevel already set).
 * Returns: list of suggestion strings.
 */
export declare function generateSuggestions(className: string, impactJson: string): Array<string>

/**
 * Hash a content string dengan algoritma pilihan.
 *
 * **Menggantikan** `hashContent(content, algorithm, length)` di `shared/src/hash.ts`.
 *
 * Algoritma yang didukung: `"md5"` (default), `"sha256"`, `"fnv"`, `"ahash"`.
 * `length` memotong output hex (mis. `8` untuk short hash cache key).
 *
 * Kecepatan dibanding JS `crypto.createHash`:
 * - `"md5"` : ~12x lebih cepat (no JS→C++ bridge overhead per call)
 * - `"fnv"` : ~40x lebih cepat (pure integer math, zero allocation)
 * - `"ahash"`: ~50x lebih cepat (SIMD-optimized, modern CPU)
 */
export declare function hashContent(content: string, algorithm?: "md5" | "sha256" | "fnv" | "ahash", length?: number | undefined | null): string

/**
 * Hash isi sebuah file — baca → hash dalam satu NAPI call.
 *
 * **Menggantikan** `hashFile(filePath, algorithm, length)` di `shared/src/hash.ts`.
 *
 * Returns `"00000000"` jika file tidak bisa dibaca.
 *
 * Lebih efisien dari JS karena satu system call vs multiple JS bridges.
 */
export declare function hashFile(filePath: string, algorithm?: "md5" | "sha256" | "fnv" | "ahash", length?: number | undefined | null): string

/** Hash a file's content for change detection. */
export declare function hashFileContent(content: string): string

export declare function hasTwUsage(source: string): boolean | null

export declare function hasTwUsage(source: string): boolean

/**
 * Deteksi dan hoist tw component declarations dari function body ke module scope.
 *
 * Menggantikan `hoistComponents` di componentHoister.ts.
 * Component yang didefinisikan di dalam render function akan direcreate
 * setiap render — Rust mendeteksi ini dan memindahkannya ke module scope.
 *
 * # Performance
 * String scanning dengan Regex Rust ~3x lebih cepat dari JS equivalent
 * karena tidak ada overhead prototype chain dan V8 JIT warmup.
 */
export declare function hoistComponents(source: string): HoistResult

export interface HoistResult {
  /** Source code setelah hoisting */
  code: string
  /** Nama komponen yang di-hoist */
  hoisted: Array<string>
  /** Warning messages */
  warnings: Array<string>
}

/** Number of active generator handles. */
export declare function idRegistryActiveCount(): number

/**
 * Create a new ID generator. Returns an opaque handle (u32).
 *
 * Replaces `createIdGenerator()` in `shared/src/schemas.ts`.
 * The handle must be passed to `id_registry_generate` and `id_registry_destroy`.
 */
export declare function idRegistryCreate(): number

/**
 * Destroy the generator and free its memory.
 *
 * Call when the generator is no longer needed (e.g. after CSS parse completes).
 */
export declare function idRegistryDestroy(handle: number): void

/**
 * Generate the next ID for `name` in the given generator.
 *
 * Replaces `generateId(gen, name)` in `shared/src/schemas.ts`.
 * Returns the assigned numeric ID. Subsequent calls with the same name
 * still increment the counter but overwrite the mapping — same semantics
 * as the JS implementation.
 */
export declare function idRegistryGenerate(handle: number, name: string): number

/**
 * Look up the ID previously assigned to `name`.
 * Returns -1 if not found or handle is invalid.
 */
export declare function idRegistryLookup(handle: number, name: string): number

/** Get the current counter value (next ID that would be assigned). */
export declare function idRegistryNext(handle: number): number

/**
 * Reset the generator to initial state (nextId=0, ids={}).
 * Cheaper than destroy+create for repeated use.
 */
export declare function idRegistryReset(handle: number): void

/**
 * Export all name→id mappings as JSON.
 * Useful for serialization / debugging.
 */
export declare function idRegistrySnapshot(handle: number): string

export interface ImpactScore {
  className: string
  /** 0.0–1.0: seberapa banyak class ini dipakai */
  usageScore: number
  /** 0.0–1.0: seberapa besar kontribusi CSS size */
  sizeScore: number
  /** Skor gabungan (weighted) */
  impactScore: number
  usageCount: number
  sizeBytes: number
}

export interface IncrementalDiff {
  addedClasses: Array<string>
  removedClasses: Array<string>
  changedFiles: Array<string>
  unchangedFiles: number
}

/**
 * Representasi satu file hasil scan di boundary NAPI.
 * Tidak punya `hash` — itu ada di `FileScanEntry` (engine.rs) untuk diff.
 */
export interface IncrementalFileEntry {
  file: string
  classes: Array<string>
}

export declare function isAlreadyTransformed(source: string): boolean | null

export declare function isAlreadyTransformed(source: string): boolean

/**
 * Check whether a class name matches any critical positioning/display pattern.
 *
 * Replaces `isCriticalClass(className)` in `ImpactTracker`.
 */
export declare function isCriticalClass(className: string): boolean

export interface KeyframeEntry {
  offset: string
  classes: string
}

/**
 * Generate a stable cache key for a named keyframes definition.
 *
 * Replaces `keyframesCacheKey(name, stops)` in `animate/src/registry.ts`.
 *
 * Input: name string + stops JSON (`{ "0%": "...", "100%": "..." }`)
 * Output: `"name::[{offset,classes},...]"` string.
 */
export declare function keyframesCacheKey(name: string, stopsJson: string): string

export interface KnownClassResult {
  className: string
  isKnown: boolean
  variantKey: string
  baseClass: string
  utilityPrefix: string
  isArbitrary: boolean
}

/**
 * Konversi layout class string menjadi inline CSS declaration string.
 *
 * **Menggantikan** `layoutClassesToCss()` di `core/src/containerQuery.ts`.
 *
 * Handles:
 * - Named layout classes (`flex`, `grid-cols-3`, dll) via static lookup
 * - Arbitrary width: `w-[320px]` → `width:320px`
 * - Arbitrary max-width: `max-w-[640px]` → `max-width:640px`
 *
 * # Examples
 * ```
 * layout_classes_to_css("flex flex-col items-center")
 * // "display:flex;flex-direction:column;align-items:center"
 *
 * layout_classes_to_css("w-[320px] grid-cols-3")
 * // "width:320px;grid-template-columns:repeat(3,minmax(0,1fr))"
 * ```
 */
export declare function layoutClassesToCss(classes: string): string

/**
 * Parse CSS rules dan merge declarations (last-write-wins).
 *
 * Menggantikan `mergeDeclarationMap` + `declarationMapToString` di classToCss.ts.
 * Dipakai saat multiple classes produce overlapping CSS properties.
 */
export declare function mergeCssDeclarations(cssChunks: Array<string>): CssDeclarationMap

export interface NativeScanFileResult {
  file: string
  classes: Array<string>
  hash: string
}

/**
 * Normalize, deduplicate, dan sort class list.
 *
 * Menggantikan `normalizeClasses` + manual Set dedup di classMerger.ts.
 * Lebih efisien karena pakai HashSet Rust tanpa GC overhead.
 *
 * # Behavior
 * - Trim whitespace
 * - Hapus duplikat (case-sensitive)
 * - Pertahankan urutan kemunculan pertama (stable dedup)
 * - Hapus empty strings
 */
export declare function normalizeAndDedupClasses(raw: string): NormalizeResult

/**
 * Normalisasi class input string menjadi Vec<String>.
 *
 * **Menggantikan** `normalizeClassInput()` di `analyzer/src/classToCss.ts`.
 *
 * Dipanggil tiap class compilation — hot path. Rust split_whitespace
 * jauh lebih cepat dari JS split(/\s+/) karena tidak butuh RegExp engine.
 *
 * # Examples
 * ```
 * normalize_class_input("bg-red-500  p-4".into())
 * // ["bg-red-500", "p-4"]
 * ```
 */
export declare function normalizeClassInput(input: string): Array<string>

/**
 * Normalize an iterations value ("infinite" | number string).
 *
 * Replaces `normalizeIterations(value)` in `animate/src/registry.ts`.
 */
export declare function normalizeIterations(value: string): string

/**
 * Normalize a numeric value with a fallback.
 *
 * Replaces `normalizeNumber(value, fallback)` in `animate/src/registry.ts`.
 */
export declare function normalizeNumber(value: number, fallback: number): number

export interface NormalizeResult {
  /** Class string yang sudah dinormalisasi */
  normalized: string
  /** Jumlah duplikat yang dihapus */
  duplicatesRemoved: number
  /** Jumlah class unik */
  uniqueCount: number
}

/**
 * Extract Tailwind classes using real Oxc AST parser.
 * Handles: tw.tag``, tw(Comp)``, base:"", className="", cx()/cn()
 * More accurate than regex — understands JSX, TypeScript, template literals.
 */
export declare function oxcExtractClasses(source: string, filename: string): OxcExtractResult

export interface OxcExtractResult {
  classes: Array<string>
  componentNames: Array<string>
  hasTwUsage: boolean
  hasUseClient: boolean
  imports: Array<string>
  engine: string
}

/**
 * Parse a single Tailwind class into an AtomicRule JSON string, or null string if unknown.
 *
 * JS equivalent: `parseAtomicClass(twClass: string): AtomicRule | null`
 */
export declare function parseAtomicClass(twClass: string): string | null

/**
 * Parse a single Tailwind class into an AtomicRule.
 *
 * Replaces `parseAtomicClass(twClass)` in `atomic/src/index.ts`.
 * Uses DashMap global registry — subsequent calls for same class are O(1).
 * Returns `null` when the class prefix is not in the property map.
 */
export declare function parseAtomicClass(twClass: string): AtomicRule | null

export declare function parseClasses(input: string): Array<ParsedClass>

export declare function parseClasses(raw: string): Array<ClassToken>

/**
 * Parse raw class string — menggantikan parseClasses() di syntax/src/index.ts.
 * Filter token kosong, validasi karakter, deduplicate.
 *
 * Lebih cepat dari JS karena regex Rust tidak perlu JIT warmup
 * dan tidak ada prototype chain overhead.
 */
export declare function parseClassesFromString(raw: string): Array<string>

/**
 * Parse CSS string dan buat reverse lookup index.
 *
 * Menggantikan `parseCSS()` + `findByProperty()` di reverseLookup.ts.
 * Dipakai oleh `tw trace` CLI dan devtools untuk debug class → property mapping.
 *
 * Input: raw CSS string dari Tailwind output.
 * Output: list of { className, property, value, ... } yang bisa difilter.
 */
export declare function parseCssRules(css: string): Array<CssRuleLookup>

/**
 * Parse CSS ke flat rule list — menggantikan parseRules() + parseSelector() di cssToIr.ts.
 *
 * Lebih cepat dari JS karena:
 * - Regex Rust tidak perlu JIT warmup per-call
 * - Tidak ada prototype chain lookup overhead
 * - Zero allocation untuk borrowed string slices
 *
 * Dipakai oleh engine trace, tw why, dan devtools inspector.
 */
export declare function parseCssToRules(css: string, prefix?: string | undefined | null): Array<ParsedCssRule>

export interface ParsedClass {
  raw: string
  base: string
  variants: Array<string>
  modifierType?: string
  modifierValue?: string
}

export interface ParsedCssRule {
  className: string
  property: string
  value: string
  important: boolean
  variants: Array<string>
  pseudoClasses: Array<string>
  mediaQuery?: string
  specificity: number
  layer?: string
}

/** Hasil parsing template literal — identik dengan `ParsedTemplate` di twProxy.ts. */
export interface ParsedTemplateResult {
  /** Base classes (tanpa sub-component blocks, tanpa komentar, whitespace normal) */
  base: string
  /**
   * Sub-component map sebagai JSON string: `{"icon":"h-4 w-4","badge":"px-2"}`
   * Dikirim sebagai JSON agar compatible dengan semua NAPI version.
   */
  subsJson: string
  /** Ada sub-component block atau tidak */
  hasSubs: boolean
}

export declare function parseSubcomponentBlocksNapi(template: string, componentName: string): SubcomponentParseResult

/**
 * Parse sub-component blocks dari template literal.
 * Menggantikan JS regex parser di createComponent.ts.
 *
 * # Example
 * ```ts
 * const r = native.parseSubcomponentBlocksNapi("p-4 [icon] { h-4 w-4 } flex", "tw")
 * // r.baseClasses = "p-4 flex"
 * // r.subMapJson  = "{\"icon\":\"h-4 w-4\"}"
 * ```
 */
export declare function parseSubcomponentBlocksNapi(template: string, componentName: string): SubcomponentParseResult

/**
 * Parse template literal yang sudah di-join menjadi satu raw string.
 *
 * **Menggantikan** `parseTemplate()` di `core/src/twProxy.ts`.
 *
 * Caller (TS) harus join `strings.raw` dengan expressions sebelum memanggil ini:
 * ```ts
 * const raw = strings.raw.reduce((acc, str, i) => {
 *   const expr = exprs[i]
 *   return acc + str + String(typeof expr === "function" ? "" : (expr ?? ""))
 * }, "")
 * const result = native.parseTemplate(raw)
 * ```
 *
 * # Output
 * - `base`     — class string bersih tanpa blok dan tanpa komentar
 * - `subs_json` — JSON `Record<string, string>` sub-components
 * - `has_subs` — shortcut untuk `Object.keys(subs).length > 0`
 *
 * # Examples
 * ```
 * parse_template("p-4 [icon] { h-4 w-4 } flex")
 * // base: "p-4 flex", subs_json: r#"{"icon":"h-4 w-4"}"#, has_subs: true
 *
 * parse_template("p-4 // comment
flex")
 * // base: "p-4 flex", subs_json: "{}", has_subs: false
 * ```
 */
export declare function parseTemplate(raw: string): ParsedTemplateResult

/**
 * Batch semver update check for all installed plugins.
 *
 * Replaces `PluginRegistry.checkAllUpdates()`.
 *
 * `installed_json`: `[{ name, version }]` — currently installed versions
 * `registry_json`: `PluginInfo[]` — registry with latest versions
 *
 * Returns `UpdateCheckResult[]` as JSON.
 */
export declare function pluginCheckAllUpdates(installedJson: string, registryJson: string): string

export interface PluginInfoOut {
  name: string
  description: string
  version: string
  tags: Array<string>
  official: boolean
  docs?: string
  integrity?: string
}

/**
 * Search plugins by query — matches name, description, tags (case-insensitive).
 *
 * Replaces `PluginRegistry.search(query)`.
 *
 * Input JSON: `PluginInfo[]`
 * Returns filtered + matched `PluginInfo[]` as JSON.
 *
 * Why faster: avoids JS `toLowerCase()` GC pressure on large registries.
 * All string operations stay in Rust heap.
 */
export declare function pluginSearch(pluginsJson: string, query: string): string

/**
 * Compare two semver strings.
 *
 * Replaces the inline version comparison in `PluginRegistry.checkForUpdate()`.
 * Returns `true` if `latest` > `current`.
 */
export declare function pluginSemverHasUpdate(current: string, latest: string): boolean

/**
 * Validate a plugin name against the registry naming convention.
 *
 * Replaces `PLUGIN_NAME_REGEX.test(name)` in `PluginRegistry.install()`.
 */
export declare function pluginValidateName(name: string): boolean

/**
 * Verify SHA-256 integrity of package.json content.
 *
 * Replaces `PluginRegistry.verifyIntegrity()` hash + compare.
 *
 * `expected_integrity`: e.g. `"sha256-abc123...=="` (npm subresource integrity format)
 * `content`: raw package.json string
 */
export declare function pluginVerifyIntegrity(content: string, expectedIntegrity: string): boolean

/**
 * Poll events yang terkumpul sejak poll terakhir.
 * JS harus memanggil ini secara periodik (misalnya setiap 200ms).
 * Events dikembalikan dan queue dikosongkan.
 */
export declare function pollWatchEvents(handleId: number): Array<WatchChangeEvent>

/**
 * Compute per-file class diff and update an in-memory registry.
 *
 * - `file_path`: absolute/normalized file path key.
 * - `new_classes`: latest extracted class list for this file.
 * - `content`: when `None`, file is treated as deleted and registry entry is removed.
 */
export declare function processFileChange(filePath: string, newClasses: Array<string>, content?: string | undefined | null): FileChangeDiff

/** Entry point utama — post-process raw CSS dari Tailwind JS dengan LightningCSS. */
export declare function processTailwindCssLightning(css: string): CssCompileResult

/** Post-process dengan vendor prefix sesuai target browser. */
export declare function processTailwindCssWithTargets(css: string, targets?: string | undefined | null): CssCompileResult

/**
 * Resolve PropertyId ke nama yang sudah terdaftar.
 *
 * **Menggantikan** `propertyIdToString(id)` di `engine/src/ir.ts`.
 * Returns `"P{id}"` jika tidak ditemukan — identik dengan JS fallback.
 */
export declare function propertyIdToString(id: number): string

/** Hasil prune — entries yang lolos + jumlah yang dihapus. */
export interface PruneResult {
  /**
   * Indices (0-based) dari entries yang LOLOS (tidak stale).
   * JS menggunakan ini untuk filter array aslinya.
   */
  keptIndices: Array<number>
  /** Jumlah entries yang dihapus. */
  removed: number
}

/**
 * Batch-check file existence + stale age — menggantikan loop JS yang
 * memanggil `existsSync()` satu per satu di `pruneStaleEntries()`.
 *
 * **Menggantikan** `pruneStaleEntries()` di `scanner/cache-native.ts`.
 *
 * JS: `entries.filter(e => existsSync(e.file) && ...)` — satu syscall per file,
 *     semuanya blocking di main thread.
 * Rust: batch metadata check via `std::fs::metadata()` — bisa diparalelkan
 *       dengan rayon jika entries > threshold.
 *
 * # Arguments
 * - `entries`      — array entries yang akan di-check
 * - `max_age_ms`   — threshold umur `lastSeenMs` (default 7 hari = 604_800_000)
 * - `check_exists` — jika true, hapus entries yang file-nya sudah tidak ada
 */
export declare function pruneStaleEntries(entries: Array<StaleCheckEntry>, maxAgeMs?: number | undefined | null, checkExists?: boolean | undefined | null): PruneResult

/**
 * Output `rebuildWorkspaceResult` — identik dengan `ScanWorkspaceResult` di TS.
 * NAPI otomatis konversi snake_case → camelCase: `total_files` → `totalFiles`.
 */
export interface RebuildResult {
  files: Array<IncrementalFileEntry>
  totalFiles: number
  uniqueClasses: Array<string>
}

/**
 * Rebuild workspace result dari list file — dedup + sort unique classes dalam satu pass.
 *
 * **Menggantikan** `rebuildWorkspaceResult()` di `engine/src/incremental.ts`.
 *
 * JS version: `Array.from(new Set(...))` → multiple allocations + GC.
 * Rust version: satu HashSet pre-allocated dengan kapasitas total classes → sort_unstable.
 *
 * Untuk workspace 500 file × 200 classes average: ~60ms JS → ~4ms Rust.
 */
export declare function rebuildWorkspaceResult(files: Array<IncrementalFileEntry>): RebuildResult

/**
 * Daftarkan nama untuk sebuah PropertyId.
 *
 * **Menggantikan** `registerPropertyName(id, name)` di `engine/src/ir.ts`.
 *
 * Menggunakan DashMap sehingga bisa dipanggil dari banyak thread tanpa Mutex.
 */
export declare function registerPropertyName(id: number, name: string): void

/**
 * Daftarkan nama untuk sebuah ValueId.
 *
 * **Menggantikan** `registerValueName(id, name)` di `engine/src/ir.ts`.
 */
export declare function registerValueName(id: number, name: string): void

/**
 * Resolve CSS cascade for a set of rules.
 *
 * Input JSON: `Array<{ id, property, origin, importance, layerOrder, specificity,
 *              conditionResult, insertionOrder }>`
 *
 * Output JSON: `{ resolutions: Array<{ id, propertyId, winnerId, loserIds,
 *               stage, finalDecision, causes }> }`
 *
 * Cascade priority: origin → layerOrder → importance → specificity → insertionOrder
 */
export declare function resolveCascade(rulesJson: string): string

/**
 * Gabungkan class names — filter falsy, join dengan spasi, normalisasi whitespace.
 *
 * **Menggantikan** `cn()` di `core/src/cx.ts`.
 *
 * Equivalent JS:
 * ```js
 * inputs.filter(Boolean).join(" ").replace(/\s+/g, " ").trim()
 * ```
 *
 * # Examples
 * ```
 * resolve_class_names(vec!["p-4".into(), "".into(), "flex".into()])
 * // "p-4 flex"
 *
 * resolve_class_names(vec!["bg-red-500  ".into(), "  text-white".into()])
 * // "bg-red-500 text-white"
 * ```
 */
export declare function resolveClassNames(inputs: Array<string>): string

/**
 * Simple variant resolution - no compound variants support
 * Faster for simple use cases
 */
export declare function resolveSimpleVariants(base: string | undefined | null, variants: Record<string, Record<string, string>>, defaults: Record<string, string>, props: Record<string, string>): string

/**
 * Resolve a CSS custom property chain like `var(--color-primary)` → concrete value.
 *
 * `raw_map` is a JSON object string: `{"key": "value", ...}` (the `theme.raw` dict).
 * Cycles are broken after 32 hops. Returns empty string if key is not in the map.
 */
export declare function resolveThemeValue(key: string, rawMapJson: string): string

/**
 * Resolve variants based on props - called from TypeScript cv() wrapper.
 * This is the hot path - executed thousands of times per build.
 */
export declare function resolveVariants(configJson: string, propsJson: string): VariantResult

/**
 * Find all classes that set `property` to any value — grouped by value.
 *
 * Replaces `ReverseLookup.findByProperty()` in `reverseLookup.ts`.
 */
export declare function reverseLookupByProperty(css: string, property: string): Array<ReverseLookupResult>

/**
 * Current number of CSS strings in the cache.
 *
 * Useful for observability / diagnostics in devtools.
 */
export declare function reverseLookupCacheSize(): number

/**
 * Evict all entries from the CSS rule cache.
 *
 * Call from JS when the CSS bundle changes (watch mode / HMR).
 * Replaces `ReverseLookup.clearCache()` in `reverseLookup.ts`.
 */
export declare function reverseLookupClearCache(): void

/**
 * Find all classes that share a base name with `class_name` (variant dependents).
 *
 * Replaces `ReverseLookup.findDependents()` in `reverseLookup.ts`.
 */
export declare function reverseLookupFindDependents(css: string, className: string): Array<string>

/**
 * Find all CSS classes that produce `property: value`.
 *
 * Replaces `ReverseLookup.fromCSS()` in `reverseLookup.ts`.
 *
 * Returns `[]` when no match. Uses DashMap cache — subsequent calls with the
 * same CSS string are O(n_rules) filter only, no re-parse.
 */
export declare function reverseLookupFromCss(css: string, cssProperty: string, cssValue: string): Array<ReverseLookupResult>

export interface ReverseLookupResult {
  property: string
  value: string
  usedInClasses: Array<ClassUsageResult>
}

export interface RouteClassMap {
  /** Route path (e.g. "/dashboard", "/api/users") */
  route: string
  /** Unique classes dipakai di route ini */
  classes: Array<string>
  /** Classes yang hanya dipakai di route ini (exclusive) */
  exclusiveClasses: Array<string>
  classCount: number
}

export interface RscAnalysis {
  isServer: boolean
  needsClientDirective: boolean
  clientReasons: Array<string>
  /** QA #3: Pattern-level detail untuk debugging dan devtools */
  detectedPatterns: Array<string>
  /** QA #3: Confidence score 0-100 (100 = explicit directive found) */
  confidence: number
}

export interface SafelistCheckResult {
  /** Classes dari input yang ada di safelist */
  matched: Array<string>
  /** Classes dari input yang TIDAK ada di safelist */
  unmatched: Array<string>
  /** Total classes di safelist */
  safelistSize: number
}

/** Get cached classes for a file by content hash. Returns null on miss. */
export declare function scanCacheGet(filePath: string, contentHash: string): Array<string> | null

/** Invalidate a single cache entry (file deleted or renamed). */
export declare function scanCacheInvalidate(filePath: string): void

/** Store extraction result in the in-memory cache. */
export declare function scanCachePut(filePath: string, contentHash: string, classes: Array<string>, mtimeMs: number, size: number): void

/** Return number of entries currently in the cache. */
export declare function scanCacheStats(): ScanCacheStats

export interface ScanCacheStats {
  size: number
}

/**
 * Read a file and extract Tailwind classes + content hash in one native call.
 *
 * JS equivalent:
 *   const source = fs.readFileSync(filePath, "utf8")
 *   const hash = hashContentNative(source)
 *   return { file: filePath, classes: scanSource(source), hash }
 *
 * Eliminates the JS file read round-trip.
 */
export declare function scanFile(filePath: string): ScanFileResult

/**
 * Baca file, ekstrak Tailwind classes, dan hash kontennya dalam satu native call.
 *
 * Menggantikan 3-step JS flow di `scanner/src/index.ts`:
 *   1. `fs.readFileSync(filePath)`
 *   2. `scanSource(source)` → native extract
 *   3. `hashContentNative(source)` → native hash
 *
 * Returns `null` jika file tidak bisa dibaca.
 */
export declare function scanFileNative(filePath: string): NativeScanFileResult | null

export interface ScanFileResult {
  file: string
  classes: Array<string>
  hash: string
  ok: boolean
  error?: string
}

/**
 * Batch scan banyak file secara paralel menggunakan rayon.
 *
 * Lebih efisien dari memanggil `scan_file_native` per file dari JS —
 * eliminasi N roundtrips, pakai semua CPU core via rayon thread pool.
 *
 * File yang gagal dibaca dikembalikan dengan classes kosong + hash kosong.
 */
export declare function scanFilesBatch(filePaths: Array<string>): Array<NativeScanFileResult>

export interface ScannedFile {
  file: string
  classes: Array<string>
  hash: string
}

export interface ScanResult {
  files: Array<ScannedFile>
  totalFiles: number
  uniqueClasses: Array<string>
}

/**
 * Scan all files in a directory tree and extract Tailwind classes.
 *
 * Returns a ScanResult with per-file class lists and global unique class set.
 * This is the Rust replacement for packages/scanner/src/index.ts scanWorkspace().
 * ─ OPTIMIZATION (Phase 2): Parallel file processing with rayon
 */
export declare function scanWorkspace(root: string, extensions?: Array<string> | undefined | null): ScanResult

/**
 * Split whitespace-separated class list into individual class strings.
 *
 * Replaces `splitClasses(classList)` in `animate/src/registry.ts`.
 * Called on every animation validation pass.
 */
export declare function splitAnimateClasses(classList: string): Array<string>

/**
 * Sort keyframe stops by offset key (locale-stable ASCII sort).
 *
 * Replaces `stableKeyframesEntries(stops)` in `animate/src/registry.ts`.
 *
 * Input JSON:  `{ "0%": "opacity-0", "100%": "opacity-100" }`
 * Output JSON: `[{ "offset": "0%", "classes": "opacity-0" }, ...]` sorted by offset.
 */
export declare function stableKeyframesEntries(stopsJson: string): Array<KeyframeEntry>

/** Entry minimal untuk stale-check — hanya field yang dibutuhkan Rust. */
export interface StaleCheckEntry {
  file: string
  lastSeenMs: number
}

/**
 * Mulai watch `root_dir` secara rekursif menggunakan `notify`.
 * Events dikumpulkan di queue internal — poll dengan `poll_watch_events()`.
 * Kembalikan `handle_id` untuk menghentikan watcher.
 */
export declare function startWatch(rootDir: string): WatchStartResult

/** Hentikan watcher dengan `handle_id`. */
export declare function stopWatch(handleId: number): boolean

export interface SubComponent {
  name: string
  tag: string
  classes: string
  scopedClass: string
}

/**
 * Parse sub-component blocks from a tw`` template string.
 *
 * Input:  `"flex gap-2 [icon] { w-4 h-4 } [label] { text-sm font-medium }"`
 * Output: JSON object string `{"icon":"w-4 h-4","label":"text-sm font-medium"}`
 *
 * Returns both the base classes (blocks stripped) and sub-component map.
 */
export interface SubcomponentParseResult {
  /** Base classes with all block syntax stripped */
  baseClasses: string
  /** JSON string: Record<name, classes> */
  subMapJson: string
}

/** Result type untuk parse_subcomponent_blocks_napi */
export interface SubcomponentParseResult {
  /** Base template string dengan semua sub-component blocks dihapus */
  baseClasses: string
  /** JSON string dari HashMap<name, classes>: {"icon":"h-4 w-4","badge":"px-2"} */
  subMapJson: string
}

/** Result dari scan sub-component names */
export interface SubComponentScanResult {
  /** Semua nama sub-component yang ditemukan di codebase */
  names: Array<string>
  /** Generated TypeScript declaration content */
  dtsContent: string
  /** Jumlah file yang di-scan */
  filesScanned: number
}

export interface ThemeToken {
  key: string
  cssVar: string
  value: string
}

/**
 * Convert a space-separated string of Tailwind classes into atomic equivalents.
 *
 * Output JSON: `{ atomicClasses: string, rules: AtomicRule[], unknownClasses: string[] }`
 *
 * JS equivalent: `toAtomicClasses(twClasses: string): { atomicClasses, rules, unknownClasses }`
 */
export declare function toAtomicClasses(twClasses: string): string

/**
 * Parse a whitespace-separated class string into AtomicRules + unknown classes.
 *
 * Replaces `toAtomicClasses(twClasses)` in `atomic/src/index.ts`.
 * Hot path — called per-component render.
 */
export declare function toAtomicClasses(twClasses: string): ToAtomicClassesResult

export interface ToAtomicClassesResult {
  atomicClasses: string
  rules: Array<AtomicRule>
  unknownClasses: Array<string>
}

export interface TransformResult {
  code: string
  classes: Array<string>
  changed: boolean
  rscJson?: string
  metadataJson?: string
}

export declare function transformSource(source: string, opts?: Record<string, string> | undefined | null): TransformResult

/**
 * Convert Tailwind utility classes → semicolon-separated inline CSS declarations.
 *
 * Mirrors `twClassesToCss()` from `stateEngine.ts`.
 * Handles static lookup (TW_MAP) and common arbitrary values `[…]`.
 *
 * ```
 * tw_classes_to_css("hidden opacity-50")      // "display:none;opacity:0.5"
 * tw_classes_to_css("bg-[#f00] w-[200px]")   // "background-color:#f00;width:200px"
 * tw_classes_to_css("unknown-class")           // ""
 * ```
 */
export declare function twClassesToCss(classes: string): string

/**
 * Conflict-aware Tailwind class merger.
 *
 * Equivalent to `twMerge()` from the `tailwind-merge` JS package.
 * Later classes win; conflicting utilities in the same group are deduplicated.
 *
 * ```
 * tw_merge("p-4 p-8")          // → "p-8"
 * tw_merge("bg-red-500 bg-blue-500")  // → "bg-blue-500"
 * tw_merge("hover:p-4 hover:p-8")     // → "hover:p-8"
 * tw_merge("p-4 hover:p-8")           // → "p-4 hover:p-8"  (different variant, no conflict)
 * ```
 */
export declare function twMerge(classString: string): string

/**
 * Merge multiple class strings (variadic convenience wrapper).
 * Joins all inputs with a space, then resolves conflicts.
 */
export declare function twMergeMany(classStrings: Array<string>): string

/** tw_merge_many dengan custom separator. */
export declare function twMergeManyWithSeparator(classStrings: Array<string>, opts: TwMergeOptions): string

/** Options untuk tw_merge_with_separator */
export interface TwMergeOptions {
  /** Separator antar class (default: " ") */
  separator?: string
  /** Aktifkan debug logging (override TWS_DEBUG env) */
  debug?: boolean
}

/**
 * tw_merge dengan custom separator.
 *
 * ```ts
 * twMergeWithSeparator("p-4 p-8", { separator: "
" })
 * // → "p-8"  (output dipisah newline, tapi conflict resolution tetap jalan)
 *
 * twMergeWithSeparator("p-4 flex", { separator: " | " })
 * // → "p-4 | flex"
 * ```
 */
export declare function twMergeWithSeparator(classString: string, opts: TwMergeOptions): string

export interface UpdateCheckResult {
  name: string
  hasUpdate: boolean
  current?: string
  latest?: string
  error?: string
}

/**
 * Validate ComponentConfig — migrated dari `validateVariantConfig()` di cv.ts.
 *
 * Menggantikan pure-JS validation yang melakukan 3× Object.entries loops.
 * Rust version: satu pass per section, zero GC pressure.
 *
 * **Input**: JSON string dari ComponentConfig (variants, defaultVariants, compoundVariants)
 * **Output**: VariantValidationResult dengan errors + warnings
 *
 * # Example TS caller
 * ```ts
 * const result = native.validateVariantConfig(JSON.stringify(config))
 * ```
 */
export declare function validateVariantConfig(configJson: string): VariantValidationResult

/**
 * Resolve ValueId ke nama yang sudah terdaftar.
 *
 * **Menggantikan** `valueIdToString(id)` di `engine/src/ir.ts`.
 * Returns `"V{id}"` jika tidak ditemukan — identik dengan JS fallback.
 */
export declare function valueIdToString(id: number): string

export interface VariantResult {
  classes: string
  resolvedCount: number
}

export interface VariantSplitResult {
  variantKey: string
  base: string
  variants: Array<string>
  isArbitrary: boolean
  hasModifier: boolean
  modifier?: string
}

export interface VariantTableResult {
  /** Component ID */
  id: string
  /** JSON: Record<string, string> — combination key → merged className */
  tableJson: string
  /** Ordered variant keys */
  keys: Array<string>
  /** Default combination key */
  defaultKey: string
  /** Total combinations */
  combinations: number
}

/** Satu validation error (identik struktur dengan VariantValidationError di cv.ts) */
export interface VariantValidationError {
  /** "unknown_key" | "unknown_value" | "missing_default" | "compound_condition_missing" */
  errorType: string
  key: string
  value?: string
  message: string
}

/** Hasil validasi config (identik dengan VariantValidationResult di cv.ts) */
export interface VariantValidationResult {
  valid: boolean
  errors: Array<VariantValidationError>
  warnings: Array<string>
}

export interface WatchChangeEvent {
  kind: string
  path: string
}

export interface WatchStartResult {
  status: string
  handleId: number
}
