/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Analyse a list of (file, classes[]) pairs and return a full report.
 *
 * `files_json` is a JSON string: `[{"file":"...","classes":["cls1","cls2"]},...]`
 * This mirrors the ScanWorkspaceResult shape from @tailwind-styled/scanner.
 */
export declare function analyzeClasses(filesJson: string, root: string, topN: number): AnalyzerReport

/**
 * Analisis class usage dari scan result JSON.
 *
 * Menggantikan sebagian `BundleAnalyzer.analyzeClass()` di bundleAnalyzer.ts.
 * Batch analysis: process banyak classes sekaligus via HashMap.
 */
export declare function analyzeClassUsage(classes: Array<string>, scanResultJson: string, css: string): Array<ClassBundleInfo>

/**
 * Analisis distribusi classes per route — untuk CSS code splitting.
 *
 * Menggantikan routeCssCollector.ts logic.
 * Dipakai oleh `tw split` untuk generate per-route CSS bundles.
 *
 * Input JSON: Record<route, string[]> — map route ke daftar file
 * files_json: JSON scan result dengan file-to-class mapping
 */
export declare function analyzeRouteClassDistribution(routeFilesJson: string, scanResultJson: string): Array<RouteClassMap>

export interface AnalyzerReport {
  root: string
  totalFiles: number
  uniqueClassCount: number
  totalClassOccurrences: number
  topClasses: Array<ClassCount>
  duplicateCandidates: Array<ClassCount>
  /** Safelist: all classes that must be retained regardless of usage */
  safelist: Array<string>
}

export declare function analyzeRsc(source: string, filename: string): RscAnalysis

/**
 * Parse a source file and extract Tailwind classes using AST-level analysis.
 * More accurate than regex-only approaches — handles JSX, template literals,
 * and object configs. Implements the same interface as the oxc-based scanner.
 */
export declare function astExtractClasses(source: string, filename: string): AstExtractResult

export interface AstExtractResult {
  /** All Tailwind classes found in the file */
  classes: Array<string>
  /** Component names found (const Foo = tw.div`...`) */
  componentNames: Array<string>
  /** Whether any tw.* usage was found */
  hasTwUsage: boolean
  /** Whether the file has "use client" directive */
  hasUseClient: boolean
  /** Import statements found */
  imports: Array<string>
}

/**
 * Extract classes dari banyak files sekaligus secara parallel.
 *
 * Menggantikan loop JS di scanner yang process satu file per giliran.
 * Menggunakan Rayon thread pool yang sudah ada untuk parallel I/O + regex.
 *
 * # Performance
 * Pada proyek 200 file: ~8-12x lebih cepat dari JS sequential loop
 * karena parallel I/O dan tidak ada event loop overhead.
 */
export declare function batchExtractClasses(filePaths: Array<string>): Array<BatchExtractResult>

export interface BatchExtractResult {
  /** File path */
  file: string
  /** Classes yang diekstrak */
  classes: Array<string>
  /** Hash content file (untuk cache invalidation) */
  contentHash: string
  /** Apakah file berhasil diproses */
  ok: boolean
  /** Error message jika gagal */
  error?: string
}

/**
 * Split class menjadi komponen-komponen: variant, base, modifier.
 *
 * Menggantikan splitVariantAndBase() di semantic.ts dan utilityPrefix() logic.
 * Batch mode untuk dipakai oleh CLI dan analyzer.
 *
 * Contoh: "dark:hover:bg-blue-500/50"
 *   → { variantKey: "dark:hover", base: "bg-blue-500", modifier: "50", ... }
 */
export declare function batchSplitClasses(classes: Array<string>): Array<VariantSplitResult>

export interface BucketedClass {
  className: string
  bucket: string
  sortOrder: number
}

export interface BundleContribution {
  className: string
  sizeBytes: number
  variantChains: Array<string>
  dependencies: Array<string>
  inCss: boolean
}

export interface CacheEntry {
  file: string
  classes: Array<string>
  hash: string
  mtimeMs: number
  size: number
  hitCount: number
}

/**
 * Compute priority score for a file (SmartCache logic in Rust).
 * Higher score = process first.
 */
export declare function cachePriority(mtimeMs: number, size: number, cachedMtimeMs: number, cachedSize: number, cachedHitCount: number, cachedLastSeenMs: number, nowMs: number): number

/**
 * Read a scanner cache JSON file into structured entries.
 * Replaces the JS `ScanCache.read()` method.
 */
export declare function cacheRead(cachePath: string): CacheReadResult

export interface CacheReadResult {
  entries: Array<CacheEntry>
  version: number
}

/**
 * Write cache entries to a JSON cache file.
 * Replaces the JS `ScanCache.save()` method.
 */
export declare function cacheWrite(cachePath: string, entries: Array<CacheEntry>): boolean

/**
 * Hitung bundle contribution untuk satu atau banyak classes dari CSS.
 *
 * Menggantikan calculateBundleContribution() + extractVariantChains() +
 * extractDependencies() di bundleAnalyzer.ts.
 *
 * Batch mode: process semua classes sekaligus dengan satu CSS scan.
 * Lebih efisien dari JS yang scan CSS satu kali per class.
 */
export declare function calculateBundleContributions(classes: Array<string>, css: string): Array<BundleContribution>

/**
 * Hitung impact score per class — usage × size weighted.
 *
 * Menggantikan logic yang tersebar di impactTracker.ts + bundleAnalyzer.ts.
 * Dipakai oleh `tw analyze` untuk ranking class berdasarkan dampak ke bundle.
 *
 * Formula: impact = (usage_weight * usage_score) + (size_weight * size_score)
 */
export declare function calculateImpactScores(classes: Array<string>, scanResultJson: string, css: string, usageWeight?: number | undefined | null, sizeWeight?: number | undefined | null): Array<ImpactScore>

/**
 * Cek daftar classes terhadap safelist.
 *
 * Menggantikan Array.filter().includes() di JS yang O(n*m).
 * HashSet lookup: O(1) per class → O(n) total.
 */
export declare function checkAgainstSafelist(classes: Array<string>, safelist: Array<string>): SafelistCheckResult

export interface ClassBundleInfo {
  className: string
  usageCount: number
  filesJson: string
  bundleSizeBytes: number
  isDeadCode: boolean
}

export interface ClassConflict {
  group: string
  variantKey: string
  classes: Array<string>
  message: string
}

export interface ClassCount {
  name: string
  count: number
}

export interface ClassDiffResult {
  /** Classes yang ada di `current` tapi tidak di `previous` */
  added: Array<string>
  /** Classes yang ada di `previous` tapi tidak di `current` */
  removed: Array<string>
  /** Classes yang ada di keduanya */
  unchanged: Array<string>
  /** Apakah ada perubahan */
  hasChanges: boolean
}

export interface ClassExtractResult {
  classes: Array<string>
  componentNames: Array<string>
  hasTwUsage: boolean
  hasUseClient: boolean
  imports: Array<string>
}

/**
 * Classify dan sort Tailwind classes berdasarkan CSS property bucket.
 *
 * Menggantikan `classifyIntoBuckets` + `sortByBucket` di styleBucketSystem.ts.
 * Bucket ordering: reset → layout → spacing → sizing → typography → visual
 *                  → interaction → responsive → unknown
 *
 * # Performance
 * HashMap lookup O(1) vs JS object lookup dengan prototype chain overhead.
 */
export declare function classifyAndSortClasses(classes: Array<string>): Array<BucketedClass>

/**
 * Classify classes sebagai known/unknown Tailwind utilities.
 *
 * Menggantikan `isKnownTailwindClass()` + `utilityPrefix()` di semantic.ts.
 * Batch mode: process banyak classes sekaligus via HashSet lookups.
 */
export declare function classifyKnownClasses(classes: Array<string>, safelist: Array<string>, customUtilities: Array<string>): Array<KnownClassResult>

export interface ClassToken {
  raw: string
  type: string
}

/** Compile a from/to animation into @keyframes + animation CSS. */
export declare function compileAnimation(from: string, to: string, name?: string | undefined | null, durationMs?: number | undefined | null, easing?: string | undefined | null, delayMs?: number | undefined | null, fill?: string | undefined | null, iterations?: string | undefined | null, direction?: string | undefined | null): CompiledAnimation

/**
 * Backward compat — sekarang input adalah raw CSS, bukan class names.
 * CSS harus datang dari Tailwind JS engine.
 */
export declare function compileCss(css: string, prefix?: string | undefined | null): CssCompileResult

/** Alias untuk backward compat. */
export declare function compileCssLightning(css: string, prefix?: string | undefined | null): CssCompileResult

export interface CompiledAnimation {
  className: string
  keyframesCss: string
  animationCss: string
}

export interface CompiledTheme {
  /** Theme name (e.g. "light", "dark", "brand") */
  name: string
  /** CSS selector for this theme (e.g. ":root", "[data-theme='dark']") */
  selector: string
  /** Full CSS block: selector { --token-name: value; ... } */
  css: string
  /** All tokens in this theme */
  tokens: Array<ThemeToken>
}

/**
 * Compile a custom multi-stop @keyframes definition.
 *
 * `stops_json`: `[{"stop":"0%","classes":"opacity-0 scale-95"},...]`
 */
export declare function compileKeyframes(name: string, stopsJson: string): CompiledAnimation

/**
 * Parse a token map JSON and compile it into a CSS variable block.
 *
 * `tokens_json`: `{"color":{"primary":"#3b82f6","secondary":"#8b5cf6"},"spacing":{"sm":"0.5rem"}}`
 * `theme_name`:  "light" | "dark" | "brand" | etc.
 * `prefix`:      CSS variable prefix, e.g. "tw" → `--tw-color-primary`
 */
export declare function compileTheme(tokensJson: string, themeName: string, prefix: string): CompiledTheme

/**
 * Compile semua kombinasi variant component ke lookup table.
 *
 * Menggantikan `compileAllVariantCombinations` di staticVariantCompiler.ts.
 * Hasilkan semua permutasi variant → merged className di build time.
 * Runtime hanya perlu O(1) lookup, zero computation.
 *
 * # Input JSON format
 * ```json
 * {
 *   "componentId": "Button",
 *   "base": "px-4 py-2 font-medium",
 *   "variants": { "size": { "sm": "h-8 text-sm", "lg": "h-12 text-lg" } },
 *   "defaultVariants": { "size": "sm" }
 * }
 * ```
 */
export declare function compileVariantTable(configJson: string): VariantTableResult

export interface ComponentPropUsage {
  /** Nama component (PascalCase) */
  component: string
  /** Map prop → daftar nilai yang dipakai di JSX */
  propsJson: string
}

/**
 * Compute an incremental diff between a previous scan result and a new file scan.
 *
 * `previous_json`: JSON array of `{file, classes, hash}` from last scan.
 * `current_json`:  JSON array of `{file, classes, hash}` from current scan.
 *
 * Returns which classes were added/removed and which files changed.
 */
export declare function computeIncrementalDiff(previousJson: string, currentJson: string): IncrementalDiff

export interface ConflictDetectionResult {
  conflicts: Array<ClassConflict>
  conflictedClassNames: Array<string>
}

export interface CssCompileResult {
  css: string
  sizeBytes: number
  resolvedClasses: Array<string>
  unknownClasses: Array<string>
}

export interface CssDeclarationMap {
  /** JSON: Record<string, string> — property → value (last wins) */
  declarationsJson: string
  /** Reconstructed declaration string: "prop: val; prop: val" */
  declarationString: string
  /** Number of declarations parsed */
  count: number
}

export interface CssRuleLookup {
  className: string
  property: string
  value: string
  isImportant: boolean
  variants: Array<string>
  specificity: number
}

export interface DeadCodeResult {
  deadInCss: Array<string>
  deadInSource: Array<string>
  liveClasses: Array<string>
  totalCssClasses: number
  totalSourceClasses: number
}

/**
 * Deteksi konflik antara Tailwind classes yang di-pakai bersamaan.
 *
 * Menggantikan `detectConflicts()` di semantic.ts.
 * Contoh: `["bg-red-500", "bg-blue-500"]` → conflict group "bg".
 *
 * Input JSON: `[{ "name": "bg-red-500", "count": 3 }, ...]`
 */
export declare function detectClassConflicts(usagesJson: string): ConflictDetectionResult

/**
 * Deteksi dead code antara CSS output dan source scan result.
 *
 * Menggantikan detectDeadCode() + checkIsDeadCode() di bundleAnalyzer.ts.
 * Single O(n+m) pass via HashSet — jauh lebih efisien dari
 * JS yang scan CSS per-class: O(n*m).
 */
export declare function detectDeadCode(scanResultJson: string, css: string): DeadCodeResult

/**
 * Hitung diff antara dua class lists.
 *
 * Dipakai oleh incremental compiler untuk mendeteksi perubahan
 * class yang perlu recompile — lebih efisien dari full string compare.
 *
 * # Performance
 * HashSet-based diff: O(n+m) vs JS array indexOf O(n*m).
 */
export declare function diffClassLists(previous: Array<string>, current: Array<string>): ClassDiffResult

export declare function extractAllClasses(source: string): Array<string>

/**
 * Extract Tailwind classes from a single source file's content.
 * Handles tw`...`, tw.tag`...`, className="...", class="..." patterns.
 * ─ OPTIMIZATION (Phase 2.3): Parallel regex pattern matching
 */
export declare function extractClassesFromSource(source: string): Array<string>

export declare function extractClassesFromSource(source: string): ClassExtractResult

/**
 * Extract semua JSX component usage dari source code.
 *
 * Menggantikan `extractComponentUsage` di deadStyleEliminator.ts.
 * Mencari pola `<ComponentName prop="value" />` dan mengekstrak
 * static prop values untuk dead style elimination.
 *
 * # Performance
 * Regex-based scan: ~2-5x lebih cepat dari JS equivalent karena
 * regex engine Rust tidak perlu GC pauses dan memory layout lebih cache-friendly.
 */
export declare function extractComponentUsage(source: string): Array<ComponentPropUsage>

/**
 * Extract CSS variables referenced in a source file.
 * Returns a list of `--var-name` strings found.
 */
export declare function extractCssVars(source: string): Array<string>

export interface FileChangeDiff {
  added: Array<string>
  removed: Array<string>
}

export interface FileScanEntry {
  file: string
  classes: Array<string>
  hash: string
}

/**
 * Scan workspace untuk semua sub-component names yang dipakai,
 * lalu generate TypeScript declaration file untuk type inference otomatis.
 *
 * Output .d.ts berisi module augmentation yang membuat TypeScript
 * tahu nama sub-component tanpa user perlu declare manual.
 */
export declare function generateSubComponentTypes(root: string, outputPath?: string | undefined | null): SubComponentScanResult

/** Hash a file's content for change detection. */
export declare function hashFileContent(content: string): string

export declare function hasTwUsage(source: string): boolean | null

export declare function hasTwUsage(source: string): boolean

/**
 * Deteksi dan hoist tw component declarations dari function body ke module scope.
 *
 * Menggantikan `hoistComponents` di componentHoister.ts.
 * Component yang didefinisikan di dalam render function akan direcreate
 * setiap render — Rust mendeteksi ini dan memindahkannya ke module scope.
 *
 * # Performance
 * String scanning dengan Regex Rust ~3x lebih cepat dari JS equivalent
 * karena tidak ada overhead prototype chain dan V8 JIT warmup.
 */
export declare function hoistComponents(source: string): HoistResult

export interface HoistResult {
  /** Source code setelah hoisting */
  code: string
  /** Nama komponen yang di-hoist */
  hoisted: Array<string>
  /** Warning messages */
  warnings: Array<string>
}

export interface ImpactScore {
  className: string
  /** 0.0–1.0: seberapa banyak class ini dipakai */
  usageScore: number
  /** 0.0–1.0: seberapa besar kontribusi CSS size */
  sizeScore: number
  /** Skor gabungan (weighted) */
  impactScore: number
  usageCount: number
  sizeBytes: number
}

export interface IncrementalDiff {
  addedClasses: Array<string>
  removedClasses: Array<string>
  changedFiles: Array<string>
  unchangedFiles: number
}

export declare function isAlreadyTransformed(source: string): boolean | null

export declare function isAlreadyTransformed(source: string): boolean

export interface KnownClassResult {
  className: string
  isKnown: boolean
  variantKey: string
  baseClass: string
  utilityPrefix: string
  isArbitrary: boolean
}

/**
 * Parse CSS rules dan merge declarations (last-write-wins).
 *
 * Menggantikan `mergeDeclarationMap` + `declarationMapToString` di classToCss.ts.
 * Dipakai saat multiple classes produce overlapping CSS properties.
 */
export declare function mergeCssDeclarations(cssChunks: Array<string>): CssDeclarationMap

/**
 * Normalize, deduplicate, dan sort class list.
 *
 * Menggantikan `normalizeClasses` + manual Set dedup di classMerger.ts.
 * Lebih efisien karena pakai HashSet Rust tanpa GC overhead.
 *
 * # Behavior
 * - Trim whitespace
 * - Hapus duplikat (case-sensitive)
 * - Pertahankan urutan kemunculan pertama (stable dedup)
 * - Hapus empty strings
 */
export declare function normalizeAndDedupClasses(raw: string): NormalizeResult

export interface NormalizeResult {
  /** Class string yang sudah dinormalisasi */
  normalized: string
  /** Jumlah duplikat yang dihapus */
  duplicatesRemoved: number
  /** Jumlah class unik */
  uniqueCount: number
}

/**
 * Extract Tailwind classes using real Oxc AST parser.
 * Handles: tw.tag``, tw(Comp)``, base:"", className="", cx()/cn()
 * More accurate than regex — understands JSX, TypeScript, template literals.
 */
export declare function oxcExtractClasses(source: string, filename: string): OxcExtractResult

export interface OxcExtractResult {
  classes: Array<string>
  componentNames: Array<string>
  hasTwUsage: boolean
  hasUseClient: boolean
  imports: Array<string>
  engine: string
}

export declare function parseClasses(input: string): Array<ParsedClass>

export declare function parseClasses(raw: string): Array<ClassToken>

/**
 * Parse raw class string — menggantikan parseClasses() di syntax/src/index.ts.
 * Filter token kosong, validasi karakter, deduplicate.
 *
 * Lebih cepat dari JS karena regex Rust tidak perlu JIT warmup
 * dan tidak ada prototype chain overhead.
 */
export declare function parseClassesFromString(raw: string): Array<string>

/**
 * Parse CSS string dan buat reverse lookup index.
 *
 * Menggantikan `parseCSS()` + `findByProperty()` di reverseLookup.ts.
 * Dipakai oleh `tw trace` CLI dan devtools untuk debug class → property mapping.
 *
 * Input: raw CSS string dari Tailwind output.
 * Output: list of { className, property, value, ... } yang bisa difilter.
 */
export declare function parseCssRules(css: string): Array<CssRuleLookup>

/**
 * Parse CSS ke flat rule list — menggantikan parseRules() + parseSelector() di cssToIr.ts.
 *
 * Lebih cepat dari JS karena:
 * - Regex Rust tidak perlu JIT warmup per-call
 * - Tidak ada prototype chain lookup overhead
 * - Zero allocation untuk borrowed string slices
 *
 * Dipakai oleh engine trace, tw why, dan devtools inspector.
 */
export declare function parseCssToRules(css: string, prefix?: string | undefined | null): Array<ParsedCssRule>

export interface ParsedClass {
  raw: string
  base: string
  variants: Array<string>
  modifierType?: string
  modifierValue?: string
}

export interface ParsedCssRule {
  className: string
  property: string
  value: string
  important: boolean
  variants: Array<string>
  pseudoClasses: Array<string>
  mediaQuery?: string
  specificity: number
  layer?: string
}

/**
 * Poll events yang terkumpul sejak poll terakhir.
 * JS harus memanggil ini secara periodik (misalnya setiap 200ms).
 * Events dikembalikan dan queue dikosongkan.
 */
export declare function pollWatchEvents(handleId: number): Array<WatchChangeEvent>

/**
 * Compute per-file class diff and update an in-memory registry.
 *
 * - `file_path`: absolute/normalized file path key.
 * - `new_classes`: latest extracted class list for this file.
 * - `content`: when `None`, file is treated as deleted and registry entry is removed.
 */
export declare function processFileChange(filePath: string, newClasses: Array<string>, content?: string | undefined | null): FileChangeDiff

/** Entry point utama — post-process raw CSS dari Tailwind JS dengan LightningCSS. */
export declare function processTailwindCssLightning(css: string): CssCompileResult

/** Post-process dengan vendor prefix sesuai target browser. */
export declare function processTailwindCssWithTargets(css: string, targets?: string | undefined | null): CssCompileResult

/**
 * Simple variant resolution - no compound variants support
 * Faster for simple use cases
 */
export declare function resolveSimpleVariants(base: string | undefined | null, variants: Record<string, Record<string, string>>, defaults: Record<string, string>, props: Record<string, string>): string

/**
 * Resolve variants based on props - called from TypeScript cv() wrapper.
 * This is the hot path - executed thousands of times per build.
 */
export declare function resolveVariants(configJson: string, propsJson: string): VariantResult

export interface RouteClassMap {
  /** Route path (e.g. "/dashboard", "/api/users") */
  route: string
  /** Unique classes dipakai di route ini */
  classes: Array<string>
  /** Classes yang hanya dipakai di route ini (exclusive) */
  exclusiveClasses: Array<string>
  classCount: number
}

export interface RscAnalysis {
  isServer: boolean
  needsClientDirective: boolean
  clientReasons: Array<string>
  /** QA #3: Pattern-level detail untuk debugging dan devtools */
  detectedPatterns: Array<string>
  /** QA #3: Confidence score 0-100 (100 = explicit directive found) */
  confidence: number
}

export interface SafelistCheckResult {
  /** Classes dari input yang ada di safelist */
  matched: Array<string>
  /** Classes dari input yang TIDAK ada di safelist */
  unmatched: Array<string>
  /** Total classes di safelist */
  safelistSize: number
}

/** Get cached classes for a file by content hash. Returns null on miss. */
export declare function scanCacheGet(filePath: string, contentHash: string): Array<string> | null

/** Invalidate a single cache entry (file deleted or renamed). */
export declare function scanCacheInvalidate(filePath: string): void

/** Store extraction result in the in-memory cache. */
export declare function scanCachePut(filePath: string, contentHash: string, classes: Array<string>, mtimeMs: number, size: number): void

/** Return number of entries currently in the cache. */
export declare function scanCacheStats(): ScanCacheStats

export interface ScanCacheStats {
  size: number
}

export interface ScannedFile {
  file: string
  classes: Array<string>
  hash: string
}

export interface ScanResult {
  files: Array<ScannedFile>
  totalFiles: number
  uniqueClasses: Array<string>
}

/**
 * Scan all files in a directory tree and extract Tailwind classes.
 *
 * Returns a ScanResult with per-file class lists and global unique class set.
 * This is the Rust replacement for packages/scanner/src/index.ts scanWorkspace().
 * ─ OPTIMIZATION (Phase 2): Parallel file processing with rayon
 */
export declare function scanWorkspace(root: string, extensions?: Array<string> | undefined | null): ScanResult

/**
 * Mulai watch `root_dir` secara rekursif menggunakan `notify`.
 * Events dikumpulkan di queue internal — poll dengan `poll_watch_events()`.
 * Kembalikan `handle_id` untuk menghentikan watcher.
 */
export declare function startWatch(rootDir: string): WatchStartResult

/** Hentikan watcher dengan `handle_id`. */
export declare function stopWatch(handleId: number): boolean

export interface SubComponent {
  name: string
  tag: string
  classes: string
  scopedClass: string
}

/** Result dari scan sub-component names */
export interface SubComponentScanResult {
  /** Semua nama sub-component yang ditemukan di codebase */
  names: Array<string>
  /** Generated TypeScript declaration content */
  dtsContent: string
  /** Jumlah file yang di-scan */
  filesScanned: number
}

export interface ThemeToken {
  key: string
  cssVar: string
  value: string
}

export interface TransformResult {
  code: string
  classes: Array<string>
  changed: boolean
  rscJson?: string
  metadataJson?: string
}

export declare function transformSource(source: string, opts?: Record<string, string> | undefined | null): TransformResult

export interface VariantResult {
  classes: string
  resolvedCount: number
}

export interface VariantSplitResult {
  variantKey: string
  base: string
  variants: Array<string>
  isArbitrary: boolean
  hasModifier: boolean
  modifier?: string
}

export interface VariantTableResult {
  /** Component ID */
  id: string
  /** JSON: Record<string, string> — combination key → merged className */
  tableJson: string
  /** Ordered variant keys */
  keys: Array<string>
  /** Default combination key */
  defaultKey: string
  /** Total combinations */
  combinations: number
}

export interface WatchChangeEvent {
  kind: string
  path: string
}

export interface WatchStartResult {
  status: string
  handleId: number
}
