/**
 * staticStateExtractor.ts — Build-time State CSS Pre-generator
 *
 * Mengkoordinasi pipeline untuk mengeliminasi runtime CSS injection untuk `states` config.
 *
 * Flow:
 *   1. Walk semua source files (.ts/.tsx/.js/.jsx)
 *   2. Per file: panggil `extractTwStateConfigs()` (Rust NAPI)
 *      → temukan semua `tw.tag({ states: {...} })` calls
 *   3. Kumpulkan semua configs, panggil `generateStaticStateCss()` (Rust NAPI)
 *      → compute hash identik dengan runtime stateEngine.ts
 *      → generate CSS rules dengan selector `.tw-s-[hash][data-stateName="true"]`
 *   4. Append hasilnya ke safelist CSS file
 *
 * Hasilnya: browser load state CSS dari static file — ZERO runtime injection,
 * ZERO flicker saat component dengan states di-render.
 *
 * Dipanggil dari withTailwindStyled.ts setelah initial Tailwind CSS scan.
 *
 * @module staticStateExtractor
 */

import fs from "node:fs"
import path from "node:path"

// ── Types (mirror dari native/src/application/state_css.rs) ────────────────

export interface TwStateConfigEntry {
  tag: string
  componentName: string
  statesJson: string
  sourceFile: string
}

export interface StaticStateCssInput {
  tag: string
  componentName: string
  statesJson: string
}

export interface GeneratedStateRule {
  selector: string
  declarations: string
  cssRule: string
  componentName: string
  stateName: string
}

export interface StaticStateExtractionResult {
  /** Total source files di-scan */
  filesScanned: number
  /** Files yang punya tw() state configs */
  filesWithStates: number
  /** Total komponen dengan states ditemukan */
  componentsFound: number
  /** Total CSS rules yang di-generate */
  rulesGenerated: number
  /** Rules yang tidak bisa di-resolve (butuh Tailwind full pipeline) */
  rulesSkipped: number
  /** CSS yang siap di-append ke safelist file */
  generatedCss: string
  /** Debug: semua rules yang di-generate */
  rules: GeneratedStateRule[]
}

// ── Source file extensions yang di-scan ────────────────────────────────────

const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mts", ".mjs"])
const IGNORE_PATTERNS = ["node_modules", ".next", "dist", "build", ".git", "coverage", "__tests__"]

// ── Native bridge lazy loader ───────────────────────────────────────────────

let _native: {
  extractTwStateConfigs: (source: string, filename: string) => TwStateConfigEntry[]
  generateStaticStateCss: (inputs: StaticStateCssInput[]) => GeneratedStateRule[]
  extractAndGenerateStateCss: (source: string, filename: string) => GeneratedStateRule[]
} | null = null

function getNative() {
  if (_native) return _native
  try {
    // Pakai require dinamis — sama dengan pattern di file lain
    const mod = require("@tailwind-styled/compiler/internal") as {
      extractTwStateConfigs?: (source: string, filename: string) => TwStateConfigEntry[]
      generateStaticStateCss?: (inputs: StaticStateCssInput[]) => GeneratedStateRule[]
      extractAndGenerateStateCss?: (source: string, filename: string) => GeneratedStateRule[]
    }
    if (
      typeof mod?.extractTwStateConfigs !== "function" ||
      typeof mod?.generateStaticStateCss !== "function"
    ) {
      return null
    }
    _native = {
      extractTwStateConfigs: mod.extractTwStateConfigs,
      generateStaticStateCss: mod.generateStaticStateCss,
      extractAndGenerateStateCss: mod.extractAndGenerateStateCss ?? (
        // Fallback jika extractAndGenerateStateCss belum di-export
        (source: string, filename: string) => {
          const configs = mod.extractTwStateConfigs!(source, filename)
          if (configs.length === 0) return []
          return mod.generateStaticStateCss!(configs.map((c) => ({
            tag: c.tag,
            componentName: c.componentName,
            statesJson: c.statesJson,
          })))
        }
      ),
    }
    return _native
  } catch {
    return null
  }
}

// ── File walker ──────────────────────────────────────────────────────────────

function* walkSourceFiles(dir: string): Generator<string> {
  let entries: fs.Dirent[]
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return
  }

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)

    if (entry.isDirectory()) {
      if (IGNORE_PATTERNS.some((p) => entry.name === p || entry.name.startsWith(p))) continue
      yield* walkSourceFiles(fullPath)
    } else if (entry.isFile()) {
      const ext = path.extname(entry.name)
      if (SOURCE_EXTENSIONS.has(ext)) yield fullPath
    }
  }
}

// ── CSS generation header ────────────────────────────────────────────────────

function buildCssHeader(result: StaticStateExtractionResult): string {
  return [
    "/* ─────────────────────────────────────────────────────────────────────",
    " * tw-state-static.css — Auto-generated by staticStateExtractor.ts",
    " * DO NOT EDIT. Re-generated on each build.",
    " *",
    ` * Files scanned:      ${result.filesScanned}`,
    ` * Files with states:  ${result.filesWithStates}`,
    ` * Components found:   ${result.componentsFound}`,
    ` * Rules generated:    ${result.rulesGenerated}`,
    ` * Rules skipped:      ${result.rulesSkipped} (akan di-inject runtime sebagai fallback)`,
    " *",
    " * Selector format: .tw-s-[hash][data-stateName=\"true\"] { ... }",
    " * Hash identik dengan yang dibuat oleh stateEngine.ts di runtime.",
    " * ─────────────────────────────────────────────────────────────────── */",
    "",
  ].join("\n")
}

// ── Main API ─────────────────────────────────────────────────────────────────

/**
 * Scan semua source files di `srcDir`, extract tw() state configs,
 * generate static CSS, dan return hasilnya.
 *
 * @param srcDir Root directory untuk scan (biasanya `process.cwd()/src`)
 * @param options Optional configuration
 */
export function extractStaticStateCss(
  srcDir: string,
  options: {
    /** Emit debug logging */
    verbose?: boolean
    /** Max files untuk di-scan (default: unlimited) */
    maxFiles?: number
  } = {}
): StaticStateExtractionResult {
  const { verbose = false, maxFiles = Infinity } = options

  const native = getNative()
  if (!native) {
    if (verbose) {
      process.stderr.write(
        "[tw:static-state] native module tidak tersedia — skip static CSS pre-generation\n"
      )
    }
    return {
      filesScanned: 0,
      filesWithStates: 0,
      componentsFound: 0,
      rulesGenerated: 0,
      rulesSkipped: 0,
      generatedCss: "",
      rules: [],
    }
  }

  // ── Step 1: Collect all configs dari semua source files ──────────────────

  const allConfigs: TwStateConfigEntry[] = []
  let filesScanned = 0
  let filesWithStates = 0

  for (const filePath of walkSourceFiles(srcDir)) {
    if (filesScanned >= maxFiles) break

    let source: string
    try {
      source = fs.readFileSync(filePath, "utf-8")
    } catch {
      continue
    }

    filesScanned++

    // Quick pre-filter — skip files tanpa states config
    if (!source.includes("states:") && !source.includes("states :")) continue
    if (!source.includes("tw.") && !source.includes("tailwind-styled")) continue

    const configs = native.extractTwStateConfigs(source, filePath)
    if (configs.length > 0) {
      filesWithStates++
      allConfigs.push(...configs)
      if (verbose) {
        process.stderr.write(
          `[tw:static-state] ${path.relative(srcDir, filePath)}: ${configs.length} komponen\n`
        )
      }
    }
  }

  if (allConfigs.length === 0) {
    return {
      filesScanned,
      filesWithStates: 0,
      componentsFound: 0,
      rulesGenerated: 0,
      rulesSkipped: 0,
      generatedCss: "",
      rules: [],
    }
  }

  // ── Step 2: Deduplicate configs (sama statesJson dari files berbeda) ─────

  const seen = new Set<string>()
  const uniqueConfigs: StaticStateCssInput[] = []

  for (const config of allConfigs) {
    const key = `${config.tag}::${config.statesJson}`
    if (!seen.has(key)) {
      seen.add(key)
      uniqueConfigs.push({
        tag: config.tag,
        componentName: config.componentName,
        statesJson: config.statesJson,
      })
    }
  }

  // ── Step 3: Generate CSS rules ─────────────────────────────────────────────

  const allRules = native.generateStaticStateCss(uniqueConfigs)

  // Count skipped: state entries yang tidak ter-resolve
  // (rules yang declarations-nya kosong sudah di-filter oleh Rust)
  const rulesSkipped = uniqueConfigs.reduce((total, cfg) => {
    try {
      const stateMap = JSON.parse(cfg.statesJson) as Record<string, string>
      return total + Object.keys(stateMap).length
    } catch {
      return total
    }
  }, 0) - allRules.length

  // ── Step 4: Build CSS output ───────────────────────────────────────────────

  // Group rules per component untuk komentar yang informatif
  const byComponent = new Map<string, GeneratedStateRule[]>()
  for (const rule of allRules) {
    const existing = byComponent.get(rule.componentName) ?? []
    existing.push(rule)
    byComponent.set(rule.componentName, existing)
  }

  const cssBlocks: string[] = []
  for (const [componentName, rules] of byComponent) {
    cssBlocks.push(`/* ${componentName} */`)
    for (const rule of rules) {
      cssBlocks.push(`/* state: ${rule.stateName} */`)
      cssBlocks.push(rule.cssRule)
    }
    cssBlocks.push("")
  }

  const result: StaticStateExtractionResult = {
    filesScanned,
    filesWithStates,
    componentsFound: allConfigs.length,
    rulesGenerated: allRules.length,
    rulesSkipped: Math.max(0, rulesSkipped),
    generatedCss: cssBlocks.join("\n"),
    rules: allRules,
  }

  result.generatedCss = buildCssHeader(result) + result.generatedCss
  return result
}

/**
 * Extract static state CSS dan append ke safelist file.
 *
 * Dipanggil dari `withTailwindStyled.ts` setelah initial Tailwind scan.
 *
 * @param srcDir Source directory untuk scan
 * @param safelistPath Path ke safelist CSS file (akan di-append, bukan di-replace)
 * @param options Optional config
 * @returns Summary string untuk logging
 */
export function appendStaticStateCssToSafelist(
  srcDir: string,
  safelistPath: string,
  options: { verbose?: boolean } = {}
): string {
  const result = extractStaticStateCss(srcDir, options)

  if (result.rulesGenerated === 0) {
    return `[tw:static-state] tidak ada state rules yang di-generate (${result.filesScanned} files di-scan)`
  }

  try {
    // Append ke safelist — TIDAK replace — supaya Tailwind classes yang sudah ada tetap ada
    fs.appendFileSync(safelistPath, `\n\n${result.generatedCss}`, "utf-8")

    return [
      `[tw:static-state] ${result.rulesGenerated} static state rules di-generate`,
      `  → ${result.filesScanned} files scanned, ${result.filesWithStates} dengan states`,
      `  → ${result.componentsFound} components, ${result.rulesSkipped} rules skipped (fallback ke runtime)`,
      `  → appended ke ${path.basename(safelistPath)}`,
    ].join("\n")
  } catch (writeErr) {
    const msg = writeErr instanceof Error ? writeErr.message : String(writeErr)
    return `[tw:static-state] gagal append ke safelist: ${msg}`
  }
}